### ISSUE TITLE
Small screen and HTML editor

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#10]
One of mail compose screen challenges will be HTML editor (itself and it's toolbar). Either we disable HTML editing on small screens or redesign the TinyMCE toolbar.

**Comment by alecpl** [comment]
The inlite theme of TinyMCE could be an option. https://www.tinymce.com/docs/demo/inlite/

**Comment by johnajackson-zz** [comment]
Is there a use case where a user would need/use the HTML editor on small screens (i.e. mobile)? If so, is the use case large enough to justify adding it or is that something we can include on desktop only?

**Comment by alecpl** [comment]
That's a question. But anyway, when user forwards/replies to an HTML email we'd need to handle that somehow.

**Comment by johnajackson-zz** [comment]
Hmm. Is it possible to just force them to use the regular editor on mobile? Do you have any ideas as to how we can solve that?

**Comment by alecpl** [comment]
I really think that using TinyMCE is the way to go. I'm not sure if hiding it's toolbar by using inlite theme will be enough. Maybe we'd need to design a small version of the toolbar. Disabling HTML editing could be more problematic.

**Comment by johnajackson-zz** [comment]
That's totally fine with me.

**Comment by alecpl** [comment]
Ok, so inlite theme is not realy a solution, it requires inline mode which we don't use. I created a minimalistic toolbar for the editor in small screen and enable autoresize feature (so there's no vertical scrollbar inside the editor).

However, I see tinymce menus do not work/fit good with a small screen. So, there will be more work on this needed.

**Comment by marclaporte** [comment]
FYI, RainLoop Webmail uses both CKEditor and Bootstrap:
https://github.com/RainLoop/rainloop-webmail/tree/master/vendors

In my tests on mobile (of RainLoop), the toolbar looked OK, but I had trouble selecting text to make it bold because my browser thinks I want to copy-paste.

Are we fully committed to TinyMCE?

**Comment by alecpl** [comment]
TinyMCE is my preference. It's used e.g. by Wordpress. We have some functionality around the editor so it might be hard to get the same with CKEditor, e.g. spellchecker. I see also that TinyMCE devs are going to give more love to usability on mobile soon, so there's a chance menus will not be a problem anymore and we can get something very nice. Of course I know CKEditor devs are also quite active and work hard on a new version, but I tried a few times in the past and there always were some quirks or missing features comparing to what we have now.

**Comment by alecpl** [comment]
Tested recently TinyMCE 4.7.4 with mobile theme. I'm not happy with the result. https://github.com/tinymce/tinymce/issues/4115

**Comment by alecpl** [comment]
Done. We'll re-consider when TinyMCE 5 is stable.
