### ISSUE TITLE
Creating and/or editing contacts: Adding birthday by keyboard only possible if you know the expected format.

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#101]
Everybody failed to enter a date via keyboard during our usetest.
The default behavior is to only accept YYYY-MM-DD. This is not a common format in German.
Therefor everyone tried to enter  DD.MM.YYYY which obviously did not work.

One part of getting this right is to select the usual format depending on the language settings.

In any case we should tell the user what format we expect. 
Some kind of placeholder text, or hint at the label.

**Comment by alecpl** [comment]
The date format is configurable via user preferences, but I agree we should display it in the input placeholder too.

**Comment by alecpl** [comment]
Done. Requires https://github.com/roundcube/roundcubemail/commit/de544cc905fa0d952d5587b0d69d553598173495
