### ISSUE TITLE
[mobile] Redundant functions for attaching a file to an e-mail

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#102]
Steps to reproduce:

1.  compose new e-mail
2. open the menu that is marked by three dots

Actual results:
There are two functions displayed to attach a file to an e-mail: "Options and attachments" and "Attach".

https://git.kolab.org/file/data/pvmlxgbixgnulr3bhobq/PHID-FILE-h5gtqshnyuxyfeivssnf/Screenshot_2017-12-01-12-42-13.png

Expected result:
There is only one option displayed to attach a file to an e-mail.
Suggestion: Either the "Attach" function is removed or the function "Options and attachments" is splitted into "Attachments" and "Other options".

**Comment by alecpl** [comment]
Removed Attach item.
