### ISSUE TITLE
[mobile] confusing warning in the contact menu

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#103]
when you add a certain contact to a group, the expected message appears saying "Kontakte wurden dieser Gruppe hinzugefügt" (= the contact was added to this group")
--> the problem is, that this message looks like a warning because of the yellow warning sign, 
--> but in fact it is just a feedback that the action has been successful

https://git.kolab.org/file/data/ak7t2xsdjnlf7ggljbzb/PHID-FILE-tmgkxy7oitpwen2ghtu7/24259361_1712067838866997_280738405_o.png

Possible Solution: 
Something like a "green checkmark" or something similar that indicates that the action was successful.

**Comment by alecpl** [comment]
Fixed in https://github.com/roundcube/roundcubemail/commit/78aa0efa1549bbae4679a3d7d9c95f337944df7e.
