### ISSUE TITLE
[mobile] E-Mail attachments are not visible

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#104]
steps to reproduce:
compose new email
attach a file (click the “options” button with three dots, click attach and add a file)

https://git.kolab.org/file/data/vr2zhq25sxtksgn6p7to/PHID-FILE-qzrd2fds7geccnuim36h/IMG_7608.PNG

problem:
It is not visible that the file is attached in the composing interface.

**Comment by alecpl** [comment]
The Attach item is redundant (as noted in another ticket), so if we remove it, user will have to use Compose and Attachments option, which will show him attachments list. I think that will be good enough.

I was also thinking about a status bar, that would be displayed only on phones, positioned between compose headers and body. That would display attachment icon when there are any attachments attached, locker icon when encryption is enabled, etc. I'm not sure if non-clickable icons will be not confusing.

**Comment by alecpl** [comment]
Done. https://kolabian.wordpress.com/2018/10/29/elastic-status-bar-for-mail-compose-options-on-mobile/
