### ISSUE TITLE
[mobile] (feature request)  primary action button (e.g. "compose new email") on the start screen

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#107]
The primary action (creating a new email / new contact/...) is currently well hidden and not directly accessible from the first screen. 

Android solves this nicely with the floating action button. 
https://guides.codepath.com/android/floating-action-buttons

Could we do something similar for elastic ?

**Comment by alecpl** [comment]
I was thinking about the same, but maybe we could use the list footer, instead of a floating button. Should the button be visible in the list view only or also when you preview some existing contact information and in the sidebar view?

**Comment by mbohlender** [comment]
Only in the listview I think.
Putting it in the footer is not a good idea in my opinion.
Currently the actions in  the footer of the listview are there to manipulate the listview
If we add the "new mail " button there, we break the mental model.

**Comment by alecpl** [comment]
Implemented.
