### ISSUE TITLE
[mobile] Inconsistent use of colors 

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#108]
How to reproduce:
E.g. try to save a change in settings 
or compose an email 
or click on "option" in the "mail" area

Actual results:
All buttons are black (they turn blue only when clicked on).

https://git.kolab.org/file/data/czw44b2qitqm6qqbhlbj/PHID-FILE-dqv64u6pxin6hqmqy3ul/IMG_4549.PNG
https://git.kolab.org/file/data/zsosqjfuqs36je5oufbk/PHID-FILE-fc7j4al7ljna3q33euhx/IMG_4552.PNG
https://git.kolab.org/file/data/zqpoocbyuy3qk6kxbg64/PHID-FILE-nnm6bwhtlidqb4omrqgo/IMG_4550.PNG

Expected/Desired results:
Colors of buttons should be adapted to kind of action AND then used consistently throughout the program.

This means: 
All buttons which are black at the moment AND which stand for the successful end of an action (e.g. "Save", "Send") should be green (because green stands for: "success"/"everything ok").
Conversely, all buttons which are black AND stand for ending/breaking off an action (e.g. "Cancel") should be red (because red stands for: "watch out"/"do you really want to end this?").

Note: As far as composing an email is concerned, the question is if both buttons should be made green because actually "Save" as well as "Send" do both stand for "successful ends of an action". It might thus be senseful to make both buttons green, but make the "Send" button stand out a bit more - e.g. simply by making it bigger.

Note: These comments on "appropriate" use of colors are not valid for "simple actions" such as "edit"!

**Comment by alecpl** [comment]
I do not fully agree. Success is a status, not button. Also, we have some buttons that have "enabled" state (e.g. Spellcheck), there we use green. For other buttons we have one more color-based state, it.s "default action" (or "main action"). For such cases we use the blue color.

Anyway, on phones it need to be still though. I think it will not be an issue if we stay with black only buttons on phones (or white if we decide to make the footer/header background dark). Need more thinking.

**Comment by alecpl** [comment]
Done.
