### ISSUE TITLE
[mobile] Bug: Tapping the search function in contact menu while composing a new e-mail leads me back to the composing interface

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#109]
Steps to reproduce:

compose new e-mail
tap the menu item "Kontakte" (= Contacts) in the menu that is marked by three dots
tap the magnifier symbol in the upper right corner
Actual results:
The search bar opens for a moment, but then I am immediately led back to the composing interface without being able to use the search bar.

Expected result:
The search bar should stay there until the user closes it.

happens on on android.
iphone seems fine

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
