### ISSUE TITLE
Login screen vs. watermark image

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#11]
The logon screen on a phone
![screen shot 2017-01-17 at 17 29 15](https://cloud.githubusercontent.com/assets/546788/22029415/cacfa016-dcda-11e6-935e-a6b157a2382a.png)
and on a bigger screen
![screen shot 2017-01-17 at 17 28 48](https://cloud.githubusercontent.com/assets/546788/22029419/ceec464a-dcda-11e6-9520-bdcea121e71d.png)
That's "designed" by me and of course looks pretty ugly. We need:

0. design the login screen and
1. create a nice "photo-like" image that would fit better to it
2. create another one or the same image that would look good as a watermark image on the "empty content frames" used inside Roundcube UI.

**Comment by johnajackson-zz** [comment]
When you say "photo-like", are you referring to something like this?

https://dribbble.com/shots/3194029-Fitness-App-Sign-In

Or do you have an example you can show me?

**Comment by alecpl** [comment]
Yes, something like these. Not sure what image would be good for webmail or if it should be a real or still life, but something wallpaper-like. Any ideas?

**Comment by johnajackson-zz** [comment]
I think we can play around with this to see what looks best.

**Comment by pom2ter** [comment]
Honestly the logo is not that bad, the main issue i see is its size, smaller is better for mobile instead of having fields on top of it. And adding 'Roundcube' with the logo is somewhat important.

**Comment by johnajackson-zz** [comment]
We just need to play with the logo a little. It could use a little updating to modernize it, but I don't think any major changes are needed to it at all.
