### ISSUE TITLE
No feedback when inserting a signature

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#110]
**How to reproduce:**
Insert a signature into a mail

**Actual Outcome:**
The signature appears immediately in the mail. Problem: the user might not notice it.

**Expected Outcome:**
A short feedback e.g. "Signature inserted successfully" in a centrally appearing window would be great!

**Comment by alecpl** [comment]
I agree, but not in part where you propose a centrally appearing window. I'd rather use the usual bottom message.

**Comment by alecpl** [comment]
Fixed in https://github.com/roundcube/roundcubemail/commit/f2b64779cc214d6e483aae73ac822f8a9117f9ee.
