### ISSUE TITLE
Column discrimination bad

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#111]
1. Due to the high contrast of the navigation column on the left, I didn't realise that it belongs to the program at all. Therefore, I didn't find the 'writing new mail' button.
2. there are too many columns (navigation, folders, inbox, opened mail) that are too similar and not well to discriminate.

possible solution:
Change of contrast/color
-> Change background color of the Folders Column to a light gray -> plus: navigation column becomes more discriminatable 

https://git.kolab.org/file/data/vv2qjzsouxcutlyrbfxr/PHID-FILE-oc5hpiertepf7hwzz3c5/grafik.png

we need a designer for this

**Comment by alecpl** [comment]
Yes, I mentioned that idea already in #56.

**Comment by alecpl** [comment]
Done.
