### ISSUE TITLE
[mobile] strange design of the button named "Schließen" (=close) in the main menu

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#113]
problem

the button  "Close" looks like it is not clickable (because it is gray)

https://git.kolab.org/file/data/jxaapcfhzsxy2ewjlghj/PHID-FILE-5cc3pg54j5zfrsdxo7po/24201038_1712068782200236_2141860615_o.png

**Comment by alecpl** [comment]
Yes, I was waiting for a designer with that. That's anyway probably a duplicate of #108 and #97.

**Comment by alecpl** [comment]
Fixed. Now the header has white text on dark background.
