### ISSUE TITLE
[mobile] No feedback whether a folder has been created successfully

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#115]
**Steps to reproduce:**

- create new e-mail folder
- tap "Speichern" (= Save)

**Actual results:**
There is no feedback displayed whether the new folder has been created successfully (only a white interface appears).

When you go back to the folder overview, the new folder is not displayed there. You have to view the folder overview all over again to see the new folder.

https://git.kolab.org/file/data/27r3sipbuprsriwn5dww/PHID-FILE-4tbmd734q2t4ux236kcr/Screenshot_2017-11-30-12-31-43.png

**Expected result:**
The software gives a feedback whether the new folder has been created successfully and the new folder is immediately displayed in the folder overview.

**Comment by alecpl** [comment]
I'm unable to reproduce, either it's device-specific, broken on your demo or it has been fixed already.
