### ISSUE TITLE
[Desktop & mobile] Wastebin-symbol and X-symbol for search function

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#116]
**How to reproduce:**
click on the search symbol
search for an E-Mail
click on the "x"

**actual result:**
clicking on the x-symbol leads to closing the search field. The sample of displayed E-Mails stays filtered for the searched term.
For ending the search one has to first erase the term via the wastebin symbol and than close the search window (with "x")

**Expected result**
Pressing the "x" should automatically do both: Deleting the search term and closing the serach field.

Having only one button does not rise the question, which one does what.
Combining the functions ending & closing the search eliminates the risk of not noticing an active search.
Furthermore, the symbol of a wastebin implies to result in deleting something and one is note sure that this "something" will not be the searched and found e-mails. So there is a high inhibition threshold to click on the symbol.

The task is for mobile and desktop. (Below the mobile version)

https://git.kolab.org/file/data/h6bjsnzmxeylnxcrtpjy/PHID-FILE-swycmwxzus2wmtfcaiir/Screenshot_20171129-111039.png

**Comment by alecpl** [comment]
There was no wastebin button in my initial implementation, but then I added it as an improvement ;)

I see at least one usability issue with your proposal. To close the searchbar without resetting a search you can click outside of the bar. No problem on desktop, but on phone you don't really have a place where you could tap to do this without invoking other actions.

**Comment by alecpl** [comment]
Search widget was improved in meantime.
