### ISSUE TITLE
3 column layout (order) not a good fit for composer

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#118]
While the 3 column layout works great for the rest of the application, it is not really a good fit for the composer.
Is it possible to change that?
switching the middle column with the right column in full mode would already be an improvement.

**Comment by alecpl** [comment]
Doable, but it would also change the order on tablets. However, I'm not sure we should break the consistency with the rest of the application pages. Maybe changing style/background color of sidebar or list (the middle column) element, proposed in another ticket would help here.

**Comment by alecpl** [comment]
Done. Composer uses two columns now.
