### ISSUE TITLE
[mobile] apparently useless button "Compare" - creating a new contact

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#119]
**steps to reproduce:**

click on the button "Kontakt" (=contact)
click on the 3 points in the top right corner
click on the button "Erstellen" (=create)
click on any of the following menu items: "Eigenschaften" (=attributes), "Personal" (=personal), "Notizen" (= notes)
click on the small button called "Vergleichen" (=compare) at the bottom of the display

**expected behaviour:**
After having clicked on that button something should happen

**actual behaviour:**

Nothing happens

Happens on iPhone

**Comment by alecpl** [comment]
This is part of Kolab History feature. It should have been disabled as it wasn't yet ported to Elastic. Anyway, it should not appear on a contact creation page. Will take a look at this. Thanks.

**Comment by alecpl** [comment]
Ah, these are indeed dialog contents (divs with id=contacthistory and id=contactdiff) from the libkolab's History functionality. They would need to have an appropriate class assigned to be hidden.

**Comment by alecpl** [comment]
Fixed on Kolab plugins side.
