### ISSUE TITLE
Text font (-family)

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#12]
So, now we have from semantic-ui:
```
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);
body {
    font-family:Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
}
```
First of all we don't want to use external resources. Second, subset=latin is not enough for multilingual app. So, what other options do we have?

**Comment by johnajackson-zz** [comment]
Can we use a Google font like Roboto?

**Comment by alecpl** [comment]
Looks like Noto (Roboto) font might be the way to go. My worries are about the font embedding and multi-language support. I suppose we could embed "Noto Sans" and the rest will be using the default. I'm not sure I know what I'm talking about, but I'm thinking about `@font-family: Noto Sans, sans-serif;`

I'll investigate with the font package from https://www.fontsquirrel.com/fonts/noto-sans.

**Comment by alecpl** [comment]
Roboto is more compact than Noto Sans, i.e. it has smaller space between characters. I'm not sure that's good, but the font file size is 3x smaller than Noto Sans (for the same character set). So, we'll use Roboto for now.
