### ISSUE TITLE
[mobile] app switcher and back button are too close to each other 

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#120]
the app switcher and the back button are so close to each other that some testers accidentally hit the wrong button.
https://git.kolab.org/file/data/2m26fwawc2hp2uecmwfi/PHID-FILE-jtdpbk37wilcr7tcrfsd/Screenshot_20171127-173425.png

Not sure how to fix this.

**Comment by alecpl** [comment]
We could increase spacing and use margin instead of padding to make the active area smaller.

**Comment by mbohlender** [comment]
worth a try

**Comment by alecpl** [comment]
Done.
