### ISSUE TITLE
Too many envelope icons for different things

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#121]
We use the envelope icon many different things.

the mail app:
https://git.kolab.org/file/data/nfbntzfdgh4gtafefg44/PHID-FILE-mzjuckdzogrjqy23cq5f/grafik.png
should probably stay that way

"Envelope" for the mail
https://git.kolab.org/file/data/gqvplchs6js66yopuhz7/PHID-FILE-e62xwkpx37krjalxyt5b/grafik.png
might be better to use something different

To / cc / bcc:
https://git.kolab.org/file/data/767jowdcvmbpo5k57bvc/PHID-FILE-d2arsabbcswj4rqn4v3f/grafik.png
we could just get rid of the icon and make To/ CC/ BCC bigger text

**Comment by alecpl** [comment]
I agree that To/Cc/Bcc could be better, but what? https://fontawesome.com/icons?d=gallery&q=user-plus&m=free ? Note, we're limited by FontAwesome 5 Free icon set.

**Comment by mbohlender** [comment]
user-plus could work

**Comment by alecpl** [comment]
Note that the list may contain also groups. Wouldn't that confusing?

**Comment by mbohlender** [comment]
> Note that the list may contain also groups. Wouldn't that confusing?

I did not think about that. it could be an issue indeed. But I think it is an improvement over the current situation.

other ideas:
* a simple "plus" icon -> don't know if it is a good idea
* just text without an icon -> not recognizable as a button

**Comment by alecpl** [comment]
Let's stay with user-plus icon. Fixed.
