### ISSUE TITLE
[mobile] back button does not lead you back

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#122]
How to reproduce:
e.g. 
1. Go to contacts page
2. Click on the arrow

Expected outcome:
The arrow takes me back to the previous page

Actual outcome:
The different groups are shown

**Comment by alecpl** [comment]
This is the same e.g. for Mail UI and Preferences UI. The arrow icon is not perfect, I agree, it was mentioned in some other ticket for a designer consideration. Maybe this could become a folder icon. it should work for mail and contacts, but not for Preferences, Identities, etc. I'm not sure we can have one icon for all cases.

**Comment by alecpl** [comment]
Re-worked sidebar navigation and changed icons.
