### ISSUE TITLE
Misspelling of recipient´s email address cannot be corrected without deleting the whole address

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#125]
Steps to get to the problem:
Write email --> add recipient´s email address ; if recipient´s address has a mistake one can only delete the whole address but not correct it

Suggestion:
It would be helpful if one could move the curser to any character/sign of recipient´s email address. Double click on the address would be a reasonable way to activate the editing process.

**Comment by alecpl** [comment]
Implemented editing on double click.
