### ISSUE TITLE
magnifier symbol does not start keyword search

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#127]
**steps to reproduce:**
click on the magnifier symbol above the email list
type a keyword into the displayed search bar
try to cklick on the magnifier symbol on the left side of the searchbar

**actual results:**
one cannot click the maginfier symbol on the left side of te serach bar to start the keyword search. One has to press the enter key (or open the drop down menu next to the search bar and click on "search") to start the search.

**expected outcome:**
Similar to most common programs there should be a button to start the search. Mostly the symbol for this Button is a maginfier. So the magnifieren on the left side of the searchbar should be clickable and result in entering the search.

The option to start the search by pressing the enter key is common as well and should stay as an option (the third one, via the drop down menue, makes sense in some contextes and does not any harm otherwise.)

**Comment by alecpl** [comment]
This was debated many times in Roundcube's past. No search button was the preferred way, but we added the button in search options menu so confused users can find it eventually.

I think our opinion about the button comes from the fact Roundcube always was desktop-like application. Desktop apps often use only Enter to start search. E.g. Thunderbird does not have a button in search widget.

The magnifier on the left is just for aesthetic purposes, we could make it a button, but would that be really expected?

**Comment by alecpl** [comment]
Search has been re-designed in meantime.
