### ISSUE TITLE
multiple selection via shift does not work on check box

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#128]
**Steps to reproduce**
go to inbox
try to select an intervall of e-mails by using the shift function:
first by clicking into the "mail preview" (subject line and sender)
than by checking the check box

**Actual results**
the shift function olny works by clicking into the "mail preview" (subject line and sender)
the shift function does not work by selecting the e-mails via check box.

**Expected results**
the shift function should work in both cases (preview AND check box)

**Comment by alecpl** [comment]
The checkbox was mainly implemented for touch devices, but I agree that Shift-click on a checkbox should work the same as for Shift-selection outside of the checkbox.

**Comment by alecpl** [comment]
Fixed by https://github.com/roundcube/roundcubemail/commit/fbc44868810b08f2b0c92e102515bc2fafffcf9c
