### ISSUE TITLE
Adding To+, Cc+, Bcc+ via contact list is not obvious

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#129]
**Steps to reproduce:** 
1. open new email composer
2. click on "To+"

**Actual results:**
It is not possible to click on the symbols To+, Cc+, Bcc+ in the bottom left corner without having selected a contact of the contact list.
This confuses the user.

**Expected results**
The system gives a hint that the user has to select a contact before he is able to add the contact at To+, Cc+, Bcc+.
Suggestion: Hint: " You have not selected a contact yet" that is presented below the contact list.

**Comment by alecpl** [comment]
Fixed.
