### ISSUE TITLE
Disable ext-windows on mobile

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#13]
It is possible to configure Roundcube to open and compose messages in a new browser window/tab.

I think on a mobile device such feature does not have much sense and should be disabled.

**Comment by johnajackson-zz** [comment]
I think this feature should be disabled for mobile devices.

**Comment by alecpl** [comment]
Above is pretty simple and already partially implemented. However, we have attachment preview windows. Opening them in the same window (and returning from them) may be tricky as we open them (also) from the mail preview frame (not the main window). So, for them we will probably need to use ext-windows but make sure the Back button just closes the window.

**Comment by alecpl** [comment]
Other functionality that need to be handled better on phones is:
1. Printing - we can probably just hide this option
2. "Show source" - we should probably use a dialog.

**Comment by alecpl** [comment]
I think that's done.
