### ISSUE TITLE
''Select'' and "Options" button only available in mail list, not in contact list

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#130]
Steps to reproduce:
Open "Mail" area, open "Contacts" area.

Actual results:
There is a ''Select'' button for the mail list of the inbox which allows for example to select all the emails at once. Additionally, there is an "Options" button and a "Threads" button.
All of these three buttons ("Select", "Threads" and "Options) are missing in the "Contacts" are/under the contact list. --> inconsistency

Expected results:
For practical reasons ("select", especially "select all", and "options" might also be useful for contacts) and for reasons of consistency, the two buttons "Select" and "Options" should be added in the "Contacts" area as well (the "Threads" button is not senseful for contacts).

![image](https://user-images.githubusercontent.com/17834426/33952206-6af608be-e031-11e7-8e8b-84899e5a57c0.png)

![image](https://user-images.githubusercontent.com/17834426/33952217-779d5c3e-e031-11e7-9f54-051631e23042.png)

**Comment by alecpl** [comment]
Done.
