### ISSUE TITLE
Confusing addition of fields when creating and/or editing a contact

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#131]
**Steps to reproduce:**
Open "contacts" area, open and edit contact or create a new contact, try to add information in a field

**Problem:**
If a user wants to add certain fields to a contact (e.g. "department", or another email Adress), he must look for the corresponding fields in three different "areas" in contacts (see screenshots): two of the three "add field"-buttons are on two different sites (the second field can be found in the tab "Properties", the third one in the tab "Personal", the third field can be accessed on all three sites, because it is placed above the tabs).

--> This makes ist a) not intuitively clear, where which field can be found ( = where which information can be added), and b) is inefficient because the user needs to open and "search" all tabs and "try out" all the different drop-down-menus where a field can be added. So first, the user has to find all the three drop-down-menus/"add field"-buttons and second, he has to find out, where he can add which information.

![image](https://user-images.githubusercontent.com/17834426/33982818-4444e1f0-e0b2-11e7-9382-c8f58a561a1d.png)
![image](https://user-images.githubusercontent.com/17834426/33982828-4d736576-e0b2-11e7-9962-a113f2300cb6.png)

**Possible solution:**
"Condense" the three to only one drop-down-menu for "add field" where all the options of the formerly separated drop-down-menus are "summarized"/can be accessed.
The system should then automatically add the selected information in the corresponding place (i.e. if a new email address was added, this should be added below the already existent email addresses, if an anniversary was added, this should appear below gender and birthday, etc.)

**Comment by alecpl** [comment]
Having one very long list might also be not usable. Here we have at least 18 items. So, I'd keep the select 1. as is, and merge 2. and 3. into one. Or maybe one long list, but with use of `<optgroup>` "separators"?

**Comment by alecpl** [comment]
Let's keep it as-is for now.
