### ISSUE TITLE
[mobile] List options displayed partially cut-off

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#132]
**How to reproduce:**
Click on "options" in the inbox

**Actual Outcome:**
List options are displayed partially cut-off

**Expected Outcome:**
Display is adjusted to the screen size

**Comment by mbohlender** [comment]
![image](https://user-images.githubusercontent.com/17834426/33983610-1344919c-e0b5-11e7-8065-7ee2e51fca55.png)
![image](https://user-images.githubusercontent.com/17834426/33983614-1864cade-e0b5-11e7-86ca-8cbc350d9bb3.png)

**Comment by alecpl** [comment]
I guess this is mobile specific. What browser/os version?

**Comment by mbohlender** [comment]
Problem occurred on Iphone 6S
Android is fine

**Comment by alecpl** [comment]
Some sources say it's enough to increase font-size on inputs/selects. However, this does not work for me on iPhone with iOS11. I guess we have to disable viewport scaling on input focus using javascript. Will see how it works.

**Comment by alecpl** [comment]
I found out font-size works, but not when using less. So, we could use it, but for some inputs it wasn't perfect. We will end up with maximum-scale=1 in viewport settings.

**Comment by alecpl** [comment]
Fixed.
