### ISSUE TITLE
[mobile] program switches from 'folder' interface to' inbox' interface automatically

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#133]
When currently in the 'Folder' interface

![image](https://user-images.githubusercontent.com/17834426/33988608-1fc374e6-e0c5-11e7-861d-6317134a2b73.png)

the program switches to the 'Inbox' interface automatically.

![image](https://user-images.githubusercontent.com/17834426/33988621-2dbd7218-e0c5-11e7-926f-56de59da3e5e.png)

This only occurs when I have touched the screen/ interface before, like for example scrolling down.
When I open the 'Folder' interface and do not touch the screen, it stays as it is and the switching does not occur.

Happens on Android. Don't know about iOS.
Not reliably reproducible.

**Comment by alecpl** [comment]
I think it may be caused by list refresh on new message. Will investigate.

**Comment by alecpl** [comment]
Unable to reproduce.
