### ISSUE TITLE
Elastic not loading

### ISSUE THREAD

**Issue by svh1985** [roundcube/elastic#135]
Hi,

I've copied the theme to the skins folder, ran the lessc command and changed the theme.. but I'm getting this screen:
![preferences](https://user-images.githubusercontent.com/5213210/34295573-55207464-e70e-11e7-85fd-5b62afab7f73.jpg)

The browser's console doesn't show any errors.

I'm at Roundcube Webmail 1.2.7

Any suggestions?

Thanks!

**Comment by alecpl** [comment]
This skin is work in progress and works only with git-master.
