### ISSUE TITLE
bad icon: recycling is not what we want to do with spam

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#136]
we currently use the recycling symbol for "spam folder" and "mark as spam".
recycling is not what we want to do with spam

**Comment by alecpl** [comment]
We're limited by FontAwesome 5 Free icon set. There's no Spam/Junk icon. How about https://fontawesome.com/icons/fire?style=solid ?

**Comment by mbohlender** [comment]
fire could work. everything is better than misusing the international symbol for recycling.

**Comment by alecpl** [comment]
Done.
