### ISSUE TITLE
Can not install skin?

### ISSUE THREAD

**Issue by ozgurerdogan** [roundcube/elastic#137]
I am getitng lots of "undefined" error when compiling less files. Am I missing something? 

`lessc  taskmenu.less > taskmenu.css
NameError: .overflow-ellipsis is undefined in /var/www/html/roundcubemail-1.3.1/skins/elastic/styles/widgets/taskmenu.less on line 18, column 9:
17     a {
18         .overflow-ellipsis;
19         text-decoration: none;
`

**Comment by alecpl** [comment]
You can't compile separate files. You should only compile three files described in the README file.

**Comment by ozgurerdogan** [comment]
Ok I did so. After activating skin, I get a whole non styled page. See screenshot: https://yadi.sk/i/HVZv4Nyu3RHBiT

**Comment by alecpl** [comment]
You're aware this requires Roundcube from git-master?

**Comment by ozgurerdogan** [comment]
Sorry I am not. I tried installing developer version if you mean that. Can you please tell me how to install skin?

**Comment by alecpl** [comment]
The README file contains installation procedure.

**Comment by ozgurerdogan** [comment]
I tried both ways. 

INSTALLATION (development):
---------------------------
1. git clone https://github.com/roundcube/roundcubemail.git
2. cd roundcubemail/skins
3. git clone https://github.com/roundcube/elastic.git
4. Disable all external plugins and set devel_mode=true.


INSTALLATION (production):
--------------------------
All styles are written using LESS syntax. Thus it needs to be compiled
using the `lessc` command line tool. This comes with the `nodejs-less`
RPM package which depends on nodejs.
```
    $ lessc -x styles/styles.less > styles/styles.css
    $ lessc -x styles/print.less > styles/print.css
    $ lessc -x styles/embed.less > styles/embed.css
```
(the -x option minifies the CSS code)

References to image files from the included CSS files can be appended
with cache-buster marks to avoid browser caching issues after updating.

Run `bin/updatecss.sh --dir skins/elastic` from the Roundcube
package before packaging the skin or after installing it on the
destination system.

**Comment by svh1985** [comment]
Same here, can't get it to work.

**Comment by ozgurerdogan** [comment]
Please add a skin only so we upload it to skin folder and run it ?

**Comment by kironet** [comment]
Same :(

**Comment by mbautista** [comment]
Hello,
First thank you very much for the elastic theme, it is really cool.
Unfortunately after upgrading roundcube and elastic, that broke the theme and I can't manage to recompile the css files...
IMHO an admin sys shouldn't have to compile less files on a production mail server.
I think it would be much better if developers just kept the css files in the repo so the final user wouldn't have to recompile them.
