### ISSUE TITLE
Bug: Adding a contact to address book does not work when email is displayed in SINGLE view

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#143]
Steps to reproduce:
Open Email with double click → email is displayed in single view (adding does work in normal view, single click on email)
Click on the email address of the sender > select "add to address book"

![image](https://user-images.githubusercontent.com/17834426/35523323-e331d288-051e-11e8-9096-e308a5e1614f.png)

Actual outcome:
Adding does not work 
No notification "contact added successfully to address book"

Expected outcome:
New contact in address book and notification "contact added successfully to address book"

**Comment by alecpl** [comment]
Fixed in https://github.com/roundcube/roundcubemail/commit/dfc835eb38a08615a8d7b8d5d5700a08fe01ef7e
