### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ltybenet** [roundcube/elastic#145]
![qq 20180222145809](https://user-images.githubusercontent.com/24642395/36524579-6c98b472-17e1-11e8-82e3-32bdc2a4d51a.png)
![qq 20180222145759](https://user-images.githubusercontent.com/24642395/36524583-714d9302-17e1-11e8-98cd-09c6a0d1ff85.png)
![qq 20180222145908](https://user-images.githubusercontent.com/24642395/36524593-75cf1b8a-17e1-11e8-913b-6c912cb16da7.png)
![qq 20180222145921](https://user-images.githubusercontent.com/24642395/36524597-78e246d0-17e1-11e8-8a75-7dab6b2e7fe3.png)
![qq 20180222145711](https://user-images.githubusercontent.com/24642395/36524600-7b2356e6-17e1-11e8-88c6-19b5ae523ead.png)
![qq 20180222150352](https://user-images.githubusercontent.com/24642395/36524637-a08e9256-17e1-11e8-9d15-a04d421dacb2.png)

I can not use it normally

**Comment by alecpl** [comment]
The skin works only with git-master version of Roundcube.
