### ISSUE TITLE
colour of buttons in managesieve filter edit

### ISSUE THREAD

**Issue by johndoh** [roundcube/elastic#147]
I think this is a personal pref type thing hence the issue rather than PR. In the managesieve plugin the buttons for add/delete actions/rules are blue:

![orig](https://user-images.githubusercontent.com/88682/36639265-d88231f6-1a00-11e8-96e9-2cfca762c2f2.png)

there is also a blue outline around the cog and add buttons when they are focused.

imo the buttons should be grey. all the other buttons in Elastic are grey (toolbars etc), like this:

![new](https://user-images.githubusercontent.com/88682/36639274-fd0ada5a-1a00-11e8-9ce0-19c1ba4c35e8.png)

suggestion:

```patch
--- a/styles/widgets/forms.less
+++ b/styles/widgets/forms.less
@@ -65,10 +65,12 @@ input.smart-upload {
             line-height: 2.3rem;
             height: 2.3rem;
             font-size: 1rem;
+            box-shadow: none;

             &:before {
                 &:extend(.font-icon-class);
                 content: @fa-var-plus;
+                color: @color-font;

                 @media screen and (min-width: (@screen-width-bs-phone + 1px)) {
                     margin: 0;
```

**Comment by alecpl** [comment]
I wouldn't remove the focus indicator. And the color is indeed a personal pref. Wontfix.
