### ISSUE TITLE
Can't install skin to git-master

### ISSUE THREAD

**Issue by blueJack92** [roundcube/elastic#148]
I am not able to install the skin to Roundcube git-master:
![unbenannt](https://user-images.githubusercontent.com/7409909/36933874-77a99ef2-1ee0-11e8-92cd-7172609b814d.PNG)

I already excecuted the lessc commands.

**Comment by blueJack92** [comment]
I activated devel mode and now the skin works as expected.

**Comment by alecpl** [comment]
Devel mode switches to in-browser less compilation. I don't know why it didn't work without it. Did lessc commands return some error?

BTW, the code has been merged into Roundcube repo.

**Comment by blueJack92** [comment]
No, no errors were returned by the lessc commands ...

**Comment by LukanoX** [comment]
I have the same problem but lessc returns me with this message:

"The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css"

lessc -v
lessc 3.8.1 (Less Compiler) [JavaScript]

What should be done in this case?
