### ISSUE TITLE
Refreshed logo concept

### ISSUE THREAD

**Issue by drudesign** [roundcube/elastic#149]
Hello all,
I've read the issue #11 and I'd like to participate in the design process - if you accept my input.
I'd like to introduce my concept of logo after facelifting as well as its placement on login screen.
Any feedback appreciated.

![phone](https://user-images.githubusercontent.com/38521714/38978406-9d4eab9c-43b7-11e8-8183-7b1b1efbddad.png)
![tablet](https://user-images.githubusercontent.com/38521714/38978407-9d698494-43b7-11e8-9a0f-41f2bacdd3e7.png)

**Comment by alecpl** [comment]
Not bad. Thanks for your participation. I'd like to make some notes for consideration.
1. For convenience I'd prefer the same logo image on logon screen and taskbar. Of course, the size may differ. But it's not a hard requirement.
2. Do not hesitate to redesign the logon screen.
3. Provide the watermark version of the logo for content frames.
Here's current Roundcube screenshot to help you.
![elastic-current](https://user-images.githubusercontent.com/546788/39417645-061c1c30-4c56-11e8-80e7-e20d43c84263.png)
Note that we're using the logo version without text and I think it's all right.

**Comment by drudesign** [comment]
1. It's reasonable to have same branding on both login screen and taskbar, here are concepts:
![phone_v2](https://user-images.githubusercontent.com/38521714/39469796-55e880a2-4d3a-11e8-8ae1-18010cc4fa2f.png)
![tablet_v2](https://user-images.githubusercontent.com/38521714/39469748-14c430da-4d3a-11e8-80ed-4535a8c53cd6.png)


2. I believe login screen design is optimal - I'd just center container (horizontal center line between login/pass input fields). Regarding inbox design - I had to darken left menu bar in order to expose darker section of the logo. The other option was to lighten the logo, but it doesn't look as good with contrast lowered. 
In modern UIs settings/options buttons are in general placed far right on horizontal layouts and bottom on vertical layouts and I believe it's good direction from the UX perspective:
![inbox_current_modified](https://user-images.githubusercontent.com/38521714/39468613-36c8bd0a-4d34-11e8-842a-2cdb14cc5310.png)


3. Here:
![logo_watermark](https://user-images.githubusercontent.com/38521714/39468263-71474282-4d32-11e8-9498-4a387ce64eea.png)

**Comment by thomascube** [comment]
@drudesign Might you be able and willing to provide the suggested logo variants as vector graphics?

**Comment by drudesign** [comment]
Sure:
[logo_v3.pdf](https://github.com/roundcube/elastic/files/2211167/logo_v3.pdf)

**Comment by thomascube** [comment]
Thanks a lot! Applied in [0c9494ced](/roundcube/roundcubemail/commit/0c9494cede65ba7).

**Comment by drudesign** [comment]
My pleasure :)
