### ISSUE TITLE
List record selection with a checkbox

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#15]
For lists with multi-selection enabled, e.g. mail messages list or contact list, for touch devices we should add a checkbox to each record. There's no other way for touch devices to select multiple rows.

However, should we display the checkbox on desktop?

**Comment by johnajackson-zz** [comment]
Let's take a look at that scenario. If we do not include checkboxes on the desktop version, do we double-click a row to access the email we received? So clicking a row once highlights it and clicking a row twice rapidly opens that email. Would that be a fair assumption?

**Comment by alecpl** [comment]
The usual and already implemented way on desktop-like applications is to select/open a message with one click. Multi-selecting is done by click+Ctrl/Shift key (using only keyboard is also possible). In "old" Roundcube we have two "desktop" modes. One with mail preview frame (below or on the right of the list) and one without the preview. In the latter case a double-click opens a message.

In elastic skin (at least now) we'll not implement "non-preview frame" mode. So, we can assume there's always a preview frame and single click opens a message, and Ctrl+click for multi-selection.

We don't want to change that. So, added checkbox would be redundant functionality. But from UX point of view is displaying a checkbox on the desktop an annoyance or wanted feature? On a pros side of displaying the checkbox always is no need to detect touch devices (which might not work for everyone). We should probably see what other webmailers do.

**Comment by johnajackson-zz** [comment]
Many mail apps don't include a checkbox on desktop versions. I think that our first iteration should to include a checkbox on mobile/tablet versions and not include them on the desktop version.

**Comment by alecpl** [comment]
Another thing to consider is that some mobile apps display the checkbox only in "edit mode" described in #16.

**Comment by alecpl** [comment]
Done. For now we display checkbox in all modes.
