### ISSUE TITLE
UX suggestions for message viewing (Reply to all, Archive, etc.)

### ISSUE THREAD

**Issue by marclaporte** [roundcube/elastic#152]
This is feedback from testing https://beta.kolabnow.com/apps/, which is Roundcube with the Elastic theme.

Overall: it's great!

I use daily for email. No IMAP client yet installed on my new Android BlackBerry Priv
And a bit of calendars and contacts: Not much because I have CardDAV and CalDAV via DAVdroid
Don't use the others (notes, files, etc.) because I have all that in Tiki Wiki CMS Groupware

In general, we should have buttons/icons for the most common actions and the rest should go in a global advanced/other menu.

Actions I need the most when viewing a message
* Reply
* Reply to all
* Archive
* Next/previous
* Add contact to address book (if not already a contact)

I do not need 
* Headers
* HTML/plain text switcher (I set "Compose HTML messages" to never)

Please see:
![2018-07-13_161610](https://user-images.githubusercontent.com/1004261/42713573-fd806282-86bd-11e8-944b-d869ff5fbd23.png)
![2018-07-13_165130](https://user-images.githubusercontent.com/1004261/42713574-fd92ab04-86bd-11e8-8fc7-48eccc50d8ff.png)
![screenshot_20180713-162515](https://user-images.githubusercontent.com/1004261/42713575-fda2791c-86bd-11e8-8573-4d4bad70cfb8.png)
![screenshot_20180713-162521](https://user-images.githubusercontent.com/1004261/42713576-fdb25026-86bd-11e8-8114-8d6e06a7736b.png)

**Comment by alecpl** [comment]
Cleaning up the repo. Partially addressesd. Please, re-evaluate with more recent version and create tickets on https://github.com/roundcube/roundcubemail.
