### ISSUE TITLE
A problem with installing the elastic skin

### ISSUE THREAD

**Issue by LukanoX** [roundcube/elastic#153]
Hello,

the problem is like on the screen.
![roudncube](https://user-images.githubusercontent.com/42693575/44617333-a302da00-a860-11e8-8de9-579fd84fa56b.jpg)

The lessc command returns:

"The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css."

 https://github.com/less/less-plugin-clean-css

using it does not work anyway.

lessc 3.8.1
roundcube 1.3.7

**Comment by alecpl** [comment]
This skin code has been moved to Roundcube repo. And there's just release 1.4-beta with Elastic.
