### ISSUE TITLE
Changing the favicon with elastic skin (1.4 RC1)

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/elastic#154]
I know the issue has already been opened to make changing the favicon easier but I have figured out a temporary workaround in the meantime (that may need to be updated when you upgrade your version). I believe this might be of benefit to some people.

I went through all the files to find out where the favicon was being set for this theme (after not finding the answers online). 

My search brought me to three files that referenced seemed associated: /.htaccess (line 6), /config/config.inc. php (line 47), and /program/include/rcmail_output_html. php (lines 1418, and 46) (NOTE: Line numbers might be slightly out as I have already customised a lot). I went through these files systematically in this order. 

The only change that seemed to make a difference was putting in the relative file path for my envisioned favicon on **line 46 of /program/include/rcmail_output_html. php**. 

In my case I changed this:
**protected $link_tags    = array('shortcut icon' => '');**
to
**protected $link_tags    = array('shortcut icon' => '/images/favicon.png');**

**Comment by Abatjour3407** [comment]
Point of clarity: Use relative file path **to your skin**

**Comment by alecpl** [comment]
This repository is abandoned. Please, use Roundcube main repository (git-master).

The favicon can be set using `skin_logo` option, or via `favicon` option in skin meta file.
