### ISSUE TITLE
iOS-like Edit button workflow?

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#16]
Just for consideration for mobile design. Should we implement iOS's workflow with Edit button?

You can see how it works e.g. here: http://ux.stackexchange.com/a/21281

**Comment by johnajackson-zz** [comment]
I like Apple's workflow for editing. My only immediate concern would be placement of the search icon. We can do some research on this to find out what the big players (Google, Apple, etc.) are doing.

**Comment by alecpl** [comment]
This is good when you have short list of actions to do on selected items. We however have much more than two. So, I abandon the idea for now.
