### ISSUE TITLE
Replace bootstrap popovers with something that works

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#17]
I was struggling with using bootstrap4's popover widget for Roundcube popup menus. This is so buggy and fragile solution that I failed. So, we'd need to wait until they fix it or rather find another solution (i.e. copy the custom code from Larry).

**Comment by thomascube** [comment]
Don't forget about accessibility (keyboard control, etc.) ;-)

**Comment by alecpl** [comment]
https://popper.js.org/ looks interesting. Probably still much work to implement all we need.

**Comment by alecpl** [comment]
And BTW, if we replace Bootstrap's popovers with something other or we don't get Bootstrap4 in Q3-2017 I would consider abandoning Bootstrap in favor of https://purecss.io or sth like that.

**Comment by pom2ter** [comment]
Thats one of the disadvantages when something is in alpha; any feature may be broken or buggy.
What exactly is the issue? And, i dont think i saw this one mentionned in all the exchange i've seen between you and Marc, why Bootstrap 4 instead of the very stable 3?

**Comment by alecpl** [comment]
I see they fixed some issues recently, so maybe beta will be usable. We target the end of year that's why I wanted to use most recent version, hoping Bootstrap4 will be ready or almost ready at that time. Anyway, our popover menus will be quite sophisticated, with multi-level popups and mobile support. So, we may need to implement this without bootstrap.

**Comment by alecpl** [comment]
FYI, looks like Bootstrap is also considering switching from tether to popper. https://github.com/twbs/bootstrap/pull/22444/files

**Comment by alecpl** [comment]
Implemented with most recent Bootstrap4 build.
