### ISSUE TITLE
Mobile: How to display/navigate to a sidebar

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#18]
There's a question how to display the sidebar on a phone.

1. It has been proposed that there's e.g. a folder title and a dropdown icon.
![mobile_list_header1](https://cloud.githubusercontent.com/assets/546788/23987421/ce0d40ea-0a29-11e7-9716-2a442f9df8d5.png)

But should be the sidebar with folders list displayed as a dropdown/popup? If so, what with the folders list footer (with quota indicator and buttons)?

2. In the elastic skin I already implemented this as a left-arrow button on the left of the folder name. This way we just jump to another view with full sidebar element, with standard header and footer.
![mobile_list_header](https://cloud.githubusercontent.com/assets/546788/23987382/a16936a2-0a29-11e7-93d6-95405614eb6c.png)

This way we have no problems with sidebar buttons, but the navigation might be not as clear. 

Another thing to consider is the fact that a sidebar list can contain more that just a "main navigation" objects (e.g. folders, addressbooks, settings points). Aside some related buttons/options it can contain additional lists, for example, the folders list in mail could include list of defined tags (with some additional buttons to manage tags). In addressbook we have list of saved searches, which at some point can also be added for mail.

Another case where we'd like to redesign the current UI is managesieve plugin UI. Currently there's four elements (settings navigation, list of scrtipts, list of rules, content frame). We should use only three main elements, i.e. we need somehow redesign the scripts list functionality.

**Comment by johnajackson-zz** [comment]
Google Inbox actually places their folder navigation within the hamburger menu. So from the hamburger menu, you'd be able to see your inbox, drafts, trash, etc. What are your thoughts on something like that?

It looks like this: https://s-media-cache-ak0.pinimg.com/236x/4c/07/a1/4c07a11803dc8c6ff3d05bc191b9c20f.jpg

**Comment by alecpl** [comment]
Where's the standard task menu there? What with folder related actions/buttons?

**Comment by alecpl** [comment]
I think we could consider putting the sidebar entry in the hamburger (tasks) menu, as a first entry. So, in Mail UI we could have "Folders" entry there, and in Addressbook UI "Groups/Searches" (or sth like that), in Settings UI we add "Settings sections". This is still an additional move/touch for the finger.

And do not forget about middle-size screens where we hide the sidebar element, but display the menu, i.e. we do not have the hamburger menu. Adding an item to the menu that is always visible, may be confusing or hard to style to make it obvious/less confusing.

**Comment by pom2ter** [comment]
Having the current hamburger menu as a sidebar, instead of a menu, on the left side of 40-50 px with icons with no text could be a way to have fewer 'clicks' to navigate. Or doing the same with folders (icons with no text on left side). In these situations the hamburger icon could be use to widen the sidebar so text/labels could be displayed..

**Comment by johnajackson-zz** [comment]
I'm working on a couple of basic wireframes to showcase potential solutions. I'll post them tomorrow.

**Comment by mbohlender** [comment]
Using option 1. would fix #122 and #120

**Comment by alecpl** [comment]
Improved over time. I consider this fixed now.
