### ISSUE TITLE
Mobile: contact preview v. edit mode

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#2]
Let's consider following steps on a mobile device:
1. Goto Contacts
2. Select a contact from the list
3. Click "Edit" button

Here:
- what action should be assigned to "Back" button, back to the list or back to contact info? I think it should point to the contact info as it was the last "view". However, a question follows: Maybe we should not display contact info in the first place and use only an "edit form" view for viewing contacts? Note that we do not have "info page" for identities/responses/folders, we do have for email though.
- should we display Cancel button? It think we should not.

**Comment by johnajackson-zz** [comment]
I envision a 'back' button taking you to your previous screen.

**Comment by alecpl** [comment]
Sure, but it's not only about the Back button. It's about UI unification. Email is specific, compose and preview are two very different things there. However, are contacts so specific? I think not. It could be handled the same way as identities, folders, etc. This means we could get rid of contact preview and use contact edit form only. That of course would mean we need a proper design of the contact edit form, so it looks good for viewing information and e.g. in read-only mode.

ps. if we consider for example some kolab plugins, like calendar, tasklist, kolab_notes. They are also inconsistent in this area (notes do not use preview, events/tasks do). I think it should be possible and reasonable to unify in a way where we do not use "preview mode", but only "edit mode" everywhere (except email).

**Comment by tpayen** [comment]
Hi Alec, to my opinion, on a mobile device, contact info page is essential to send a message with the mailto link or to call directly from the page (mixing information and editing could confuse people)

**Comment by alecpl** [comment]
That's a good point. I suppose we stay with preview mode for contacts. So, I'd consider consistency in not using the preview mode to apply only for Settings section.
