### ISSUE TITLE
Make 'loading' message less disturbing?

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#20]
Some people complain that the 'loading' messages are disturbing. Some people complained about "Draft has been saved" message disturbing too. While I do not share that opinion, I'm curious if we could make it better?

**Comment by pom2ter** [comment]
Not sure i understand. Do you mean intrusive? How those messages can be considered as disturbing.

Maybe making them smaller could be better..

**Comment by alecpl** [comment]
I mean they draw user's attention when they should not, but that's only some people's opinion. I don't think it's a highly common opinion, but something to consider. Especially now when we design also a mobile UI.

**Comment by johnajackson-zz** [comment]
As long as they aren't insanely flashy, I don't see these things as problems. Any idea what percentage of users have this opinion? We can always make them less intrusive and more user-friendly.

**Comment by alecpl** [comment]
On the other hand there are users that complained about the message do not get enough attention to the user. So, I think current compromise is good.
