### ISSUE TITLE
Checkbox on lists potentially confusing

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#22]
We use checkboxes on lists for multi-selection. On other lists, e.g. folder subscriptions list, we use checkboxes to switch subscription flag. I think that might be confusing. Maybe we should leave checkbox for selection, but replace all other uses with something else. One solution comes to my mind, a two-state icon/button. An On/Off button (without labels), e.g. as in iOS would be fine, I suppose.

Another story is how user-friendly are on/off switches without labels on phones. I think on folders list it would be not so bad. Other uses may require a label or a different two-state icon.

**Comment by pom2ter** [comment]
You mean like this ? 

![iosstylebutton](https://cloud.githubusercontent.com/assets/104492/24982718/ecbb184a-1fb0-11e7-86ce-d9406b98638a.png)

The off button could have a red background and/or the entire row could be a different color depending if its on or off to make it more noticeable.

On/off switch could be done in CSS.  (one example: https://proto.io/freebies/onoff/ )

Note: if you decide to use colors with no labels, best to not use red *and* green which will make it difficult for people with color blindness.

**Comment by alecpl** [comment]
Yes, for some use-cases a "button" based on e.g. star and star-o icons could work too, i suppose. We'll have to think about each functionality when we get there. For example calendar plugin uses a three switch buttons on the calendars list, but in places with many switches we might just replace all of them with one menu (where we can put text labels).

**Comment by johnajackson-zz** [comment]
I agree. We should determine a consistent behavior for various elements. Something like this, perhaps, could work.

<img width="510" alt="screen shot 2017-06-05 at 12 02 55 pm" src="https://cloud.githubusercontent.com/assets/25418507/26792009/02b94e2c-49e7-11e7-9632-bd507b8acf59.png">

**Comment by alecpl** [comment]
FYI, simple implementation for Bootstrap: https://github.com/twbs/bootstrap/pull/23004

**Comment by alecpl** [comment]
Done with custom solution based on font-awesome icons.
