### ISSUE TITLE
Create some common images

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#23]
Together with graphic design we'll need some images for common functionality:
- favicon.ico
- watermark.jpg
- contactgroup.png (created using font-awesome icon image)
- contactpic.png (created using font-awesome icon image)
- filedrop.png
- quota.png (highly depends on a design of the quota widget)
- roundcube_logo.png

See https://github.com/roundcube/roundcubemail/tree/master/skins/larry/images for Larry version.

**Comment by pom2ter** [comment]
favicon could be the same, its quite nice and i like it.
the filedrop could be an arrow with a dashed outline done in css.

**Comment by EleonoraL** [comment]
Hello everyone, I'm going to start working on this issue and create the missing images

**Comment by alecpl** [comment]
I did what I could. Closing for now.
