### ISSUE TITLE
Design mail compose layout

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#25]
This have to be designed carefully for all screen sizes. I just wanted to provide some ideas. I'm really not a designer, so it's ugly, but focus on the position of elements not how they look like, please ;)

![elastic-compose](https://cloud.githubusercontent.com/assets/546788/24767267/ba95d9a6-1afe-11e7-91b4-234086ff8c07.png)

So, the addressbook in a sidebar, compose options and attachments in the middle box, headers and body in the content box. This way on a tablet we can just hide the sidebar and show it on request. On mobile we display only the content box, sidebar and options on request (from the menu). Another idea is the plain vs. html mode switch being tabs, but that are details that are less important.

In my opinion that will be cleaner and better than what we have in larry skin now.

There are some plugins that add compose options e.g. Enigma. This layout will make then better visible (not hidden in toolbar with popups).

**Comment by johnajackson-zz** [comment]
I can design a basic mock-up for this and we can figure out a good way to lay out these components that can be mobile-friendly, too.

**Comment by johnajackson-zz** [comment]
My initial recommendation would be to keep everything as simple as possible. Companies like Google have done a fantastic job at creating workflows that are simple and straight-to-the-point. Here are some initial thoughts I have:

**We're showing too many input fields by default**
An email always has a sender and it always has a recipient. However, it does not always need to include a CC, BC, etc. If we show all of these options by default, we're going to create unnecessary noise for the end-user.

**Does a user need all of those WYSIWYG options?**
Have you considered an approach similar to Google's Inbox, where we show them the most popular options, such as Bold, Italics, Underline, etc. and group the others in a dropdown?

**My hopes are to lessen cognitive load on users**
As a user, my goal is to compose an email. If I need to CC someone, I can expand my "To" selection within the dropdown and add a CC. If I need to bold something, I can click the Bold icon or I can select another option from the text-edit drop down if necessary.

Having too much going on can distract the user and make them less efficient at a task. We do not want to overwhelm the user with options that they'll rarely use. The people who are 100% going to use those options will take the extra click to use them.

<img width="591" alt="screen shot 2017-06-09 at 2 45 29 pm" src="https://user-images.githubusercontent.com/25418507/26990185-c7cb72fa-4d23-11e7-9603-b733f6cec3ea.png">

**Comment by alecpl** [comment]
My screenshot was done on a very early state. If you see current demo, there's much less fields visible by default. Generally From, To, Subject and body (in the main area). So, that is agreed.

As for the HTML options and HTML vs. Plain switch. I of course considered limiting number of options, especially on mobile, but this is not trivial to implement. I think we could probably limit the number of buttons to one line (like half of what we use now). There will always be power users that want more options there. I also considered removing switching of modes as we could automatically detect if user used formatting or not, but it might be tricky. Again, power users very often do not use HTML at all and e.g. replacing standard plain text quoting characters with something HTML-ish might be not welcome.

The other compose options like attachments, priority, target folder, or encryption options is another story. Some of them need to be visible all the time, some could be hidden. The fact is we have a good place for them in that 3-column layout. It's a matter of a design if it should be on left or right from the main content area or the way of focus the user on the main area not options.

**Comment by johnajackson-zz** [comment]
What are some examples where users would need to use HTML but wouldn't be able to perform the same task using the WYSIWYG buttons instead?

**Comment by alecpl** [comment]
I don't understand the question. Let's assume we can simplify the toolbar in a similar way you proposed. Still I think we need HTML vs. plain switch. Also, wouldn't better be make subject and body inputs more visible? How would that look when input is focused?

**Comment by alecpl** [comment]
I'm closing this one as done.
