### ISSUE TITLE
Style "Restore message?" dialog buttons

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#27]
The dialog that is used on mail compose has three buttons:
1. Restore - should have an icon
2. Delete - should use some (red?) background color
3. Ignore - should have an icon.

**Comment by pom2ter** [comment]
It could be possible to use fontawesome for those. like times-circle for delete (so a coloured background would be easy) and minus-circle for ignore. For restore, it could be the refresh icon but its a bit of a stretch.

**Comment by alecpl** [comment]
Yes, fontawesome everywhere where possible ;) This ticket is just a reminder for me or maybe I should create "Junior Job" tag, in case anyone wanted to work on such simple tasks?

**Comment by alecpl** [comment]
Done.
