### ISSUE TITLE
Use dialogs instead of content frames for some functionality

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#3]
In my opinion we made a mistake by displaying advanced search in a content frame. I think content frames should be used only for displaying content of the main list items (or creating these items).

So, I propose to use dialog popups for these "additional" functionalities like advanced search.

I would do the same with contacts import (mail import, calendar import, both use popup).

For example kolab_addressbook plugin uses the content frame for addressbook folder creating/editing form. This should also be done in a popup window.

**Comment by thomascube** [comment]
Agreed.

**Comment by alecpl** [comment]
Done in dev-elastic branch of Roundcube core.
