### ISSUE TITLE
Roundcube support for 'related messages'

### ISSUE THREAD

**Issue by hachre** [roundcube/elastic#31]
Is Roundcube going to get support for 'related messages'? I'm asking because I think users will expect a workflow like that from an app that has a 3 pane layout as it is proposed here.

What I mean is something similar to threads, but it also includes messages across folders (including your own replies). This way when you click a new message in the middle pane, you'd see the entire history of conversation (no matter where those messages are from) in the right pane. 

I also believe this is a key ingredient for a modern mail client.

Is this planned?

**Comment by alecpl** [comment]
No one is working on this and this would be a big task. I don't think I'd work on such a feature. Not for Roundcube 1.4 which is the target for Elastic.

**Comment by hachre** [comment]
Thanks.
