### ISSUE TITLE
carddav.css 

### ISSUE THREAD

**Issue by TaiCuong** [roundcube/elastic#37]
I wasn't able to get this skin to work
I compiled on my local : 

lessc -version
lessc 2.7.2 (Less Compiler) [JavaScript]

lessc -x styles/styles.less > styles/styles.css
The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css.

so I remove the -x and didn't get any messages

uploaded to server 
and ran 

bin/updatecss.sh --dir /skins/elastic 

generated files, and did not return any error. but the skin did not work
http://74.208.102.146/1234071023985/431570946/Aug08OWI1Yj.png

the 2 files missing in the console are 

/mail/plugins/carddav/skins/elastic/carddav.css 
/plugins/managesieve/skins/elastic/managesieve.css 

I copied managesive from larry, and could not find carddav anywhere. that did not help

any idea ?

**Comment by alecpl** [comment]
The skin does not support plugins yet, and we do not support external plugins. However, this should not cause this issue. Are you sure no other issues in console? Try with devel_mode=1. Also note that at this moment it should be used with dev-elastic branch of Roundcube not master.

The skin status is not even alpha. So, you're on your own.
