### ISSUE TITLE
Widgets: Info messages

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#38]
Provide styling (and colors) for information message boxes displayed in the right bottom corner of the screen. They are already implemented and you can see them in the demo, but we need at least colors. We need:
1. Colors for state: information, error, warning, confirmation (success info) and loading. Text, background, border. Note that we use some opacity.
2. All of them can contain text links, so we need color for them.

Note also that we use the same styling for inline messages as presented on the screenshot in #28. In this case they can contain also buttons.

**Comment by johnajackson-zz** [comment]
<img width="567" alt="screen shot 2017-09-09 at 2 08 28 pm" src="https://user-images.githubusercontent.com/25418507/30242660-6208a9dc-9568-11e7-8c86-6eaca53adaa2.png">

Thoughts on this? Why is there opacity to toast messages in the current system?

**Comment by alecpl** [comment]
Opacity is to not cover all under the element. I think it helps a little to make the message less disturbing. But I think it's not required.

I think what you propose would be ok. In old system we used different background color for different modes, but I guess icon color could work as well.

What color of a text link inside? What color for "warning" mode, some orange-yellow'ish?

**Comment by alecpl** [comment]
And what color for "loading" mode? I guess some grey'ish to make it different and even less disturbing.

**Comment by johnajackson-zz** [comment]
With the exception of the loading message, we will want toast messages to be read and understood by the user. If we lower the opacity on the messages, the users may not necessarily be as drawn to the message that we are attempting to deliver. My recommendation would be to have the toast messages shown at full opacity. 

In response to your comment about the background color, I fully agree with you. Check out this screenshot for an update and let me know your thoughts!

<img width="430" alt="screen shot 2017-09-13 at 10 54 45 pm" src="https://user-images.githubusercontent.com/25418507/30410080-f3a19fea-98d6-11e7-9df5-da71e17d9844.png">

**Comment by alecpl** [comment]
Again, I think warning should use a different color than error. Also, I feel the informative message is too dark. Also, do not forget about text links that, if you decide to use blue'ish color for them, may not look good on these backgrounds, but we could use just underline. The same will concern buttons (as described in #28). I'm not sure. Maybe these background colors are just too strong. Finally, I prefer the red color variant you used in previous proposal.

I'm not sure which version is better, maybe if I saw them as they would look like in the whole UI...

**Comment by alecpl** [comment]
I prefer the first version and I implemented it. I consider it done. Here's how it looks like right now.

![messages](https://user-images.githubusercontent.com/546788/31043287-92394f24-a5b9-11e7-8bb7-a638d043136d.png)
