### ISSUE TITLE
Widgets: Popup menus

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#39]
For popup menus we need some styling. Note that on phones they look quite different than on desktop, this can be seen in the demo.
1. Colors, shadow?
2. Style for normal item and selected item.
3. Style for labels. See Responses button menu in Compose for what I mean.

And a little related: drag-n-drop element style. It's the element that contains message subject(s) when you drag a mail message. It might use similar style to popup menus, but don't have to. The main question is should this (and menus) be dark-ish or white-ish?

**Comment by johnajackson-zz** [comment]
Are we referring to general modals like this?

<img width="724" alt="screen shot 2017-09-21 at 8 11 17 pm" src="https://user-images.githubusercontent.com/25418507/30724021-0e367b36-9f09-11e7-8f20-c074bbd50a94.png">

**Comment by alecpl** [comment]
No, it's about menus. They have not much common styling with modals even on phones.

**Comment by alecpl** [comment]
Mostly done, but as everything else some graphic designer could polish it. Closing for now.
