### ISSUE TITLE
Widgets: buttons

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#42]
We need a color palette for buttons: primary action, secondary action, delete action. Text, background, border, focus outline.

**Comment by johnajackson-zz** [comment]
<img width="485" alt="screen shot 2017-09-13 at 11 05 40 pm" src="https://user-images.githubusercontent.com/25418507/30410284-1799f9aa-98d8-11e7-8e87-04bc9526a5f7.png">

https://projects.invisionapp.com/d/main#/console/11452712/253317964/inspect

**Comment by mbohlender** [comment]
We put some work into styling our buttons in Kube with "fancy" things such as color coded action buttons for creative / destructive actions and such. Would you be interested in something like that ?

**Comment by alecpl** [comment]
@mbohlender Color palette is not yet written in stone. So, I think that maybe it could be helpful. Could you direct me to this Kube design resources or send them via email?

**Comment by alecpl** [comment]
I consider this done. If we ever have a designer working on the general layout (and color palette) it may be re-worked.
