### ISSUE TITLE
Widgets: Form layout

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#43]
We use bootstrap, but please create a style for e.g. the identity form. We need style (spacing and colors) for fieldset legend, form rows and labels.

Should fieldsets become boxes (with border and/or background)?

**Comment by johnajackson-zz** [comment]
<img width="428" alt="screen shot 2017-09-21 at 8 09 43 pm" src="https://user-images.githubusercontent.com/25418507/30723999-ec499742-9f08-11e7-9ae3-712728ab231c.png">

Thoughts on these for starters?

**Comment by alecpl** [comment]
I hesitate to use upper case for labels. We chave checkbox items in forms where the label could be a long text. And I was expecting something about general layout of a form (fieldset legend, spacing between fieldsets, etc.), not the inputs itself.

**Comment by alecpl** [comment]
Done.
