### ISSUE TITLE
INSTALLATION (production) 

### ISSUE THREAD

**Issue by visages** [roundcube/elastic#44]
After unsuccessfully installed Melanie2 mobile plugin (know issue with ROundcube 1.3 release Jquery version), I found your (responsive?) theme.

I  cloned the project into roundcube/skins, compiled ccs files into roundcube/skins/elastic/styles with less.

The last point is not clear to me : 

> Run bin/updatecss.sh --dir <path-to-kolab-skin> 

 I know a vendor/kolab directory, but no skin ? Were should I point that command too ?

Will it be enough then to get the theme working ? At the moment if I try I have a unusable result.

Thanks a lot for that skin.

**Comment by alecpl** [comment]
Fixed. It should be `bin/updatecss.sh --dir skins/elastic`. It is optional anyway.

Be warned the skin is not yet ready for use.

**Comment by visages** [comment]
Thanks a lot. I should have guessed ! By the way, below is the way it displays on desktop once the Install is finished. I suppose I missed something.

I had this error while updating css : _ERROR: Failed to load plugin file /opt/roundcube/plugins/elastic/elastic.phpImage: skins/elastic/images/watermark.jpg (e784.5000)_. It might be related.

![preferences](https://user-images.githubusercontent.com/18335154/30212564-c72d80b2-94a5-11e7-84c6-30445c6c899d.png)
