### ISSUE TITLE
Mobile: Minimum supported screen width

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#5]
I think we should not care about devices with less that 320px. Shouldn't we? That would be for example iPhone4 (which is 240px).

**Comment by thomascube** [comment]
I suggest to define the smallest screen size ("xs" in Bootstrap terminology) to 480px and everything <= 480px to use 100% width and no horizontal floating. That should then properly degrade on devices with < 240px of screen size.

**Comment by alecpl** [comment]
That's the limit we have now. Still there's a difference between 320px (imho reasonable size) and 240px. E.g. some toolbars might be too narrow to place all buttons (even the limited for phones set of buttons). Also, my Firefox (on desktop) does not allow me to change the page width to less than ~300px, so testing will be hard.

**Comment by alecpl** [comment]
Actually minimum Chrome width is 378px and for Firefox it is 275px on my system.

**Comment by thomascube** [comment]
FWIW: Chrome has a specific mode (via its debug console) where you can switch to mobile device mode and set any screen size you like.

**Comment by alecpl** [comment]
Ok, so hard development is not an argument ;) Still I think we'd need to add some css code for sizes less that 320px, but maybe it will not be much. Let's agree that our minimum SUPPORTED width is 240px.

**Comment by alecpl** [comment]
Done.
