### ISSUE TITLE
Widgets: Expand/collapse in folder list on touch devices

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#50]
The expand/collapse icon/button is too small to be usable on touch devices. What we could do?
1. Hide the icon and expand all records automatically on touch devices.
2. Make the touch area around the icon bigger (e.g. as big as the folder icon)
3. Use bigger icon and move it before the folder icon.
4. Use "long press" (taphold) event

What's best? Other options?

**Comment by alecpl** [comment]
If we decide on solution 3. we could consider making it a solution for non-touch UI too. This way maybe we could make it consistent with messages list. However, I'm not sure about this one. If there's no sub-folders on the list at all the space on the left side of the list will be wasted and do not look good.

**Comment by johndoh** [comment]
Regarding solution 4. On a touch device I think the expected behaviour of long press/taphold is to open a context menu. IMO end users may not expect it do have expand/collapse functionality without training.

**Comment by alecpl** [comment]
Right. So, let's replace the 4th option with: Use bigger icon and move it to the right side of the record.

**Comment by alecpl** [comment]
Implemented option 3 for all screen sizes.
