### ISSUE TITLE
Move .font-icon-class to mixins file

### ISSUE THREAD

**Issue by johndoh** [roundcube/elastic#51]
The .font-icon-class defined in [styles.less](https://github.com/roundcube/elastic/blob/master/styles/styles.less#L90) is going to be useful for plugins as well as the core. Right now it cannot be directly referenced because styles.less also uses the mixin and so any genereted CSS contains those classes as well as the ones from the plugin's less. If this (and other similar classes) were in a seperate mixins file then then plugins could reference that file without any danger of picking up anything else.

**Comment by alecpl** [comment]
I didn't think much about (big or external) plugins yet. I think it makes sense. PRs welcome.

**Comment by johndoh** [comment]
I did a search though the less files and it looks like its only the font-icon-class and the animation class that would be effected.

**Comment by alecpl** [comment]
Merged. Thanks.
