### ISSUE TITLE
Template include path

### ISSUE THREAD

**Issue by MarcProe** [roundcube/elastic#54]
I had the problem that no css would load.

Looking at the template files, `roundcube:include` tags are written like this
`
<roundcube:include file="includes/layout.html" />
`

Referring to the [skins documentation](https://github.com/roundcube/roundcubemail/wiki/Skins):

> All references like images, stylesheets and included files must be defined with absolute paths (starting with /) where / is the root of the skin subfolder.

I changed the include occurrences to 
`
<roundcube:include file="/templates/includes/layout.html" />
`
and everything works.

**Comment by alecpl** [comment]
You have to use dev-elastic branch. See README.

**Comment by kaedwen** [comment]
I have the same problem. No css is loading.
Where do I have to switch something?
I have done all the steps written in INSTALLATION (development) and INSTALLATION (production) but after I have copied the elastic from my dev host to the production skins/ and activated the elastic skin there text only
