### ISSUE TITLE
General layout improvement

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#56]
So, we have responsiveness, navigation and most of functionality in place. However, it was implemented by me (non-graphic-designer). The first design ideas we had wasn't completed so, I couldn't make it pretty. It's very simplistic right now. It implements functionality, but does not look pretty. Color palette is not established. Borders and backgrounds need to be designed. And general layout beauty.

1. Desktop.

For a big screen, where users see three columns (plus left-side menu)... It's pretty raw, all white, sidebar and main list the same. I'm pretty sure we can improve here. For example, the sidebar list could be different that the main list: should the middle column use different background color? Should the sidebar list (folders list in mail view) use border on list records? Font colors? Should icons on lists use the same color as text font? Things like that.
Next, the watermark image (the Roundcube logo in the content frame when no item is selected), I think it could be improved to match better this skin. It could be also replaced with something completely different. Here's one of my previous ideas (of course appropriate photo/image need to be found)

![watermark](https://user-images.githubusercontent.com/546788/31704014-afb23712-b3df-11e7-941c-e0785ffeec18.png)

2. Mobile.

On a tablet/phone the look could be simplified, so current state is close to what I'd like to see. We still need some colors here and there. Most of them would be inherited from the desktop version, but not all. E.g. We want all headers look the same, all lists and menus, look the same and consistent. We could for example use different (dark?) background color for navigation headers/footers.

**Comment by florianbeer** [comment]
You should let @sschoger take a gander at it (if he wants to). He always comes up with very awesome designs.

**Comment by Leiesoldat** [comment]
The first question is do you want the user to be able to change that graphic in the empty space or do you want a logo? If a logo, does it need to be the RC logo or can it be something different? If different, have you thought of a logo for the Elastic project? Doing a quick Google image search for the word "elastic" brings up several logos, both colored and monochrome (personally think monochrome would look better) that are good examples of what could fit in that space.

**Comment by alecpl** [comment]
We don't need a logo for Elastic, it will be an integral part of Roundcube at some point.

It does not really matter what that image is. Vendors should be able to change it to something else, e.g. their company logo. Maybe even we could allow user-configurable images. Anyway we need a nice default. So, it could be a Roundcube logo (existing one or some new one/improved) or a photo-like image (that somehow relates with what Roundcube is) or a collage.

**Comment by drudesign** [comment]
Hello,
I'd like to propose my logo concept which in my opinion fits new design:
[logo_v3.pdf](https://github.com/roundcube/elastic/files/1927162/logo_v3.pdf)

Regarding other issues, raw design is very usable, it look quite nice, although it may need very few improvements.

I'd abandon any images in background, eventually leave an option to choose one by user.

For great color schemes, you can get inspired by adobe kuler:
https://color.adobe.com/pl/explore/?filter=most-popular&time=all
I see current design is close to Flat UI https://color.adobe.com/pl/Flat-UI-color-theme-2469224/
Maybe it would be good Idea to offer few color schemes - just like Wordpress do?

Subtle border is useful on mail list, on folders - not necessarily. Also inactive folders could be painted in same colour as sender - there's no need to distract user from reading mail topics.

In general people read images better than text, so in my oppinion icons should be the same color as text, which is best close to black and a bit shifted to green and little more to blue - #141822 looks nice.

Here are fast-implemented issues that I've mentioned:
![inbox](https://user-images.githubusercontent.com/38521714/38981266-476e351e-43bf-11e8-9804-d9f0ab6deca3.png)

**Comment by alecpl** [comment]
I consider this done.
