### ISSUE TITLE
Enigma.css not found

### ISSUE THREAD

**Issue by Vitaliy-1** [roundcube/elastic#57]
Generally, after trying to install see this message in the browser console:

`GET https://.../plugins/enigma/skins/elastic/enigma.css net::ERR_ABORTED`

Is there a need to copy something additionally in this directory?

**Comment by alecpl** [comment]
Nope. Are you on most recent dev-elastic branch?

**Comment by Vitaliy-1** [comment]
Ahhh, nope.

**Comment by Vitaliy-1** [comment]
After running update script from master to dev-elastic branch skin works fine, but I get the following error:

`SMTP Error: Connection failed: Failed to connect socket: Connection refused in /var/www/.../.../program/lib/Roundcube/rcube.php on line 1672`

Or I shouldn't perform an update from a different branch?

EDIT: all worked fine before the upgrade.

**Comment by alecpl** [comment]
That's completely unrelated. And there's no need to run update script.

**Comment by Vitaliy-1** [comment]
It's just SMTP port changed in config after upgrading. Sorry for bothering. The theme works fine. Thanks!
