### ISSUE TITLE
Set minimum supported browser versions

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#6]
As we use flexbox, we develop on most recent Chrome/Firefox. I really like flexbox.
Looks like it is not supported on Android <= 4 (and Safari < 9), how old versions of browsers/devices we should support? Do we need/should use vendor-prefixed css for older browsers?

**Comment by thomascube** [comment]
I guess we're fine for now. I'd not use any vendor-prefixes. If needed, we can add an [auto-prefixer](https://github.com/less/less-plugin-autoprefix) to the CSS build step with LESS.

And hopefully, there'll be a flexbox polyfill to even support IE versions < 10.

**Comment by alecpl** [comment]
BTW. Here's semantic-ui's browser support list:

    Last 2 Versions FF, Chrome, Safari Mac
    IE 11+
    Android 4.4+, Chrome for Android 44+
    iOS Safari 7+
    Microsoft Edge 12 & 13

**Comment by alecpl** [comment]
For Bootstrap4 it is: IE10+, Edge, Last 2 versions for Chrome, Firefox, Safari, Android 5+.
