### ISSUE TITLE
Option to toggle checkboxes on message list

### ISSUE THREAD

**Issue by johndoh** [roundcube/elastic#60]
I think the checkboxes in the message list take up quite a lot of space, especially on small screens. I’ve been trying out a few things; hiding the checkboxes seems easy enough and making them show up once you start selecting messages.

A way to toggle them on a small screen is a challenge though. One idea I had was to use the Select icon in the message list footer, on first click it shows the checkboxes and once they are visible then clicking it shows the menu. I’m not sure that is very user friendly, having 2 different functions on the same button.

I wanted to open this ticket to see if there was any interest in a feature like this and to discuss options for allowing a user to toggle the display of the checkboxes.

**Comment by johndoh** [comment]
Possible solution here https://github.com/JohnDoh/elastic/tree/messagelist. Work in progress, feedback welcome.

**Comment by alecpl** [comment]
I agree the list looks better without these checkboxes. Here's my opinion about that:
1. Using existing Select button is a no-go, imho. I also not really like your automatic detection of selection mode.
2. I prefer selection checkboxes to use default style, not our pretty checkbox icon. There's one reason. If we ever add selection checkboxes to folders list in Settings > Folders we'll end up with two same checkboxes in one record, this will be confusing. So, it's better to check CHECK-boxes for selection, an SWITCH-boxes for subscription, etc. Note, there are already plugins that are in this situation.
3. In #16 I considered "Edit button selection" functionality used by some mobile clients, but it's main purpose was selection actions, which we don't really want as we have much more actions that can be taken on selected records.

However, I didn't find a perfect solution. A separate button to show checkboxes might be the best. I'd put it in list header, but we already have there quite a lot of buttons on mobile. So, I'm not sure.

**Comment by johndoh** [comment]
> 1. Using existing Select button is a no-go, imho. I also not really like your automatic detection of selection mode.

Agreed. The auto detection is a bit of a hack and if a proper solution can be found to toggle the checkboxes then its probably not needed any way.

> 2. I prefer selection checkboxes to use default style, not our pretty checkbox icon. There's one reason. If we ever add selection checkboxes to folders list in Settings > Folders we'll end up with two same checkboxes in one record, this will be confusing. So, it's better to check CHECK-boxes for selection, an SWITCH-boxes for subscription, etc. Note, there are already plugins that are in this situation.

I had not thought about the folders list in Settings > Folders. I did use different icons from the normal SWITCH-boxes. I will revert this change from my testing.

> 3. In #16 I considered "Edit button selection" functionality used by some mobile clients, but it's main purpose was selection actions, which we don't really want as we have much more actions that can be taken on selected records.

> However, I didn't find a perfect solution. A separate button to show checkboxes might be the best. I'd put it in list header, but we already have there quite a lot of buttons on mobile. So, I'm not sure.

IMO there are already a lot of buttons especially on a small screen, that's why I thought I'd try splitting the existing selection button into 2 with the main button toggling the checkboxes and the drop down for the actions. I played with the list header but I could not find I solution there that I liked.

**Comment by alecpl** [comment]
Hmm... after more thinking..., maybe the dropdown button you proposed is not a bad idea. This way we get two buttons, but visually almost one. I think I could accept that solution, until someone finds another way.

**Comment by alecpl** [comment]
However, I didn't check your changes yet, how does the dropdown button work with touch? It cannot be too small. I just found out we do not have a dropdown button in mobile anywhere except popup menus. Maybe for mobile this will have to be a normal button.

**Comment by johndoh** [comment]
For me the dropdown works ok with touch. I made the arrow slightly bigger on phones otherwise its the same as the one used in the toolbar.

I've cleaned up the code a little and now it should not affect the folder list in the settings screen, or any thing other than the message list.

**Comment by alecpl** [comment]
Do not forget about other lists. We need the same for contacts list in addressbook and in mail compose. Probably other lists in future or in plugins.

Here I see one problem. In mail compose, with enabled vcard_attachments plugin, we already have four buttons in contacts list footer, and there's not much place for another button.

So, here's another idea. Maybe we should add a button to the list navigation bar instead?

**Comment by johndoh** [comment]
Sure. I've given that a try here https://github.com/JohnDoh/elastic/tree/messagelist2

It still needs more work, this is just to get an idea of what it would look like.

**Comment by alecpl** [comment]
Implemented.
