### ISSUE TITLE
Bad Icon for "spellcheck"

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#63]
The current icon for spellchecking in the composer is  a magic wand.
It somewhat works in English:  "magic wand" -> "spell check"
but it completely breaks in German:  "zauberstab" ->  "rechtschreibprüfung"
It is very likely that it will break in other languages as well.

**Comment by alecpl** [comment]
Some icons are subject to change. Unfortunately font-awesome does not provide a better icon. Maybe there will be one in Font-awesome5.

But thanks for pointing that, we should have a list of all icon bugs.

**Comment by alecpl** [comment]
Still no better icon in FontAwesome 5.

**Comment by alecpl** [comment]
Has been fixed.
