### ISSUE TITLE
rcmail.menu_stack functionality removed in 05b030e

### ISSUE THREAD

**Issue by johndoh** [roundcube/elastic#64]
First: I realise this is still a work in progress so appoligies if I'm asking you about something that you are already working on.

Commit 05b030e overloads the show_menu/hide_menu JS functions from the core. But it also removes some core functionality. Namely the rcmail.menu_stack array. I use information from that array in my contextmenu plugin to help keep track of whats been opened. So my question is, might this functionality be added back at some point in the future or should I change contextmenu so that it does not rely on the menu_stack?

**Comment by alecpl** [comment]
I'm not sure, maybe we'll need it for keyboard navigation over menus, but I'd prefer to not have to bring the stack back. It looks to me as it complicates the code needlessly. So, if you can workaround that in your plugin it would be better.

**Comment by johndoh** [comment]
ok
