### ISSUE TITLE
Irritating background image/ symbol

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#67]
The roundcube logo, that is displayed when no mail/contact/... is selected  should be removed and replaced with a descriptive text that explains why there is an empty area. 

e.g. "no mail selected" 

![image](https://user-images.githubusercontent.com/17834426/33215449-12eaa11c-d130-11e7-84e7-dd6b09de40bf.png)

**Comment by alecpl** [comment]
I wouldn't remove it, maybe it just needs to be bigger and look more like a background. Once I proposed a photo-like background, but for this I need a graphic designer.

**Comment by alecpl** [comment]
I consider this non-issue, now with some bigger image.
