### ISSUE TITLE
buttons for copy/move contact

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#71]
There are no buttons to move/copy a contact to another folder/addressbook (or adding a contact to a group).
Similar actions are offered in the mailview. This is a consistency problem.

**Comment by alecpl** [comment]
Right. While it's possible to do this using drag-n-drop, this obviously will not work on phones. We should add a "More..." menu with copy and move actions.

**Comment by alecpl** [comment]
That requires changes in the core and will not be a simple task. Moved to https://github.com/roundcube/roundcubemail/issues/6081
