### ISSUE TITLE
better error message when "archive" fails

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#73]
When you click archive and no archive folder is set, archiving fails and you get the message
"some mails could not be archived"

Instead we should help the user fix it:

* tell him why it failed and how to fix it
even better:
* offer a "quickfix" button that opens the settings where it can be fixed

**Comment by alecpl** [comment]
This is not skin specific. Moved to https://github.com/roundcube/roundcubemail/issues/6076.
