### ISSUE TITLE
feature request: attachment reminder

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#75]
Many Email-Clients include a feature that reminds the user to add an attachment when certain keywords (e.g. "attachment", in german: "Anhang", "anbei") are mentioned in the text of the email. This function is desirable to prevent errors.

**Comment by alecpl** [comment]
Such functionality exists, Preferences > Composing Messages > Remind about forgotten attachments.

**Comment by mbohlender** [comment]
Could we change the default to enabled then?
