### ISSUE TITLE
feature request: send contact via mail from the adressbook

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#77]
Currently you have to manually download a contact and then manually attach it to a new mail if you want to share it.

A "share" button in the adressbook would be nice convenience feature.

**Comment by alecpl** [comment]
It is already possible to attach a vcard of a contact. In mail compose window there's a button in contacts list footer - if vcard_attachments plugin is enabled.

A button in Addressbook UI could also be considered a valid request.

**Comment by alecpl** [comment]
Moved to https://github.com/roundcube/roundcubemail/issues/6080 as this need to be implemented in Roundcube first.
