### ISSUE TITLE
 Log-out button is partially covered by browser information

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#78]
The log-out button is partially covered by the link preview of the browser:
Not sure if this is a big issue.

https://git.kolab.org/file/data/6kqqstebyk4tr6ckqz3j/PHID-FILE-57vunsnoml5oqhwzkfba/image.png

**Comment by alecpl** [comment]
But only when your mouse cursor is on a link. So, not all the time. It also covers other buttons labels, but I don't think we'll add a bottom margin to fix just this.
