### ISSUE TITLE
[mobile] displayed screen section does not automatically adjust by deleting text

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#79]
How to reproduce:

1. open new mail
2. write several lines so the written text fills more than the displayed area
3. delete text until the displayed area is empty.

Actual Outcome:
The displayed area does not automatically follow the curser by deleting more than the displayed text.

Expected Outcome:
One should always see the letters that are being deleted. So the display area should follow the curser. (The same way it does by writing new lines instead of deleting them)
Details

**Comment by mbohlender** [comment]
This seems to be an Android only issue.

**Comment by alecpl** [comment]
Plain text or HTML mode?

**Comment by mbohlender** [comment]
html

**Comment by alecpl** [comment]
There's probably nothing we can do about this issue. Either TinyMCE will fix this or we replace the editor. Closing for now.
