### ISSUE TITLE
Design list/sidebar footers

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#8]
We need to design layout and logic (in all screen sizes) of the following functionality:
- list navigation (first, prev, next, last buttons) and counters
- list action buttons e.g. add/delete contact, add/delete response, etc., folders list actions
- quota indicator (less important)

**Comment by alecpl** [comment]
```
-----------------------------------------------------------------
|   (icon)   |   (icon)   |    <<        <         >        >>  |
|    main    |  optional  |             X - Y of ZZZZ           |
-----------------------------------------------------------------
```
I was thinking about using what we have now, but with some changes and unification:
1. There can be only one main button for "Add" action (be it add contact, add folder, etc., for mail it could be "Compose" button).
2. There can be only one optional button. So if we want to put more actions here the optional button will be "More actions" button with popup menu.
3. Buttons will have an icon + text below the icon, i.e. the footer will be bigger in height than the header.
4. The "More actions" button in a popup could have "List options" position, which was placed in (messages) list header. I think this might be not bad idea as we don't really have enough room in the header. In small-screen mode that menu could contain also (some) content toolbar and sidebar items.
5. The navigation widget would look more or less as above. Maybe depending on its width we could place text in the middle of the "arrows bar".

Question:
Should have additional main button for "Delete" action? If we decide for two main buttons (Add and Delete) we'd probably need to think about a layout for small screen where three buttons + navigation widget could be too much.

Note:
We should also review sidebar and toolbar actions that should be put in "More actions" menu on main lists. E.g. for mail view it would be Reply/Reply-All/Forward/Mark etc. but also Import, Compact, Empty, Mark all as read. For example in Addressbook the "Save search" action should be in this menu. Of course, on phones, some most-used actions like Reply/Forward/Delete/Mark could be placed in a separate toolbar, e.g. above the footer.

**Comment by alecpl** [comment]
Here's a list of actions to consider (core + some plugins):
1.Mail messages:
1.1. Single message actions: Reply, Reply-All, Forward, Delete, Archive, Junk, Mark, Print, Download, Edit (and Edit as new), Show source, Move, Copy, Create filter, Save as event, Save as Task, Add a note.
1.2. Multiple-selection actions: Forward, Delete, Archive, Junk, Mark, Move, Copy.
1.3. Non-selection actions: Import, Compose, Refresh.
2. Mail Folders actions: Compact, Empty, Mark all as read, Manage folders, Manage tags (if we add kolab tags list to the folders list).
3. Contacts list actions: Add, Delete, Compose, Print (single-selection only), Import, Export, Remove selected from group.
4. Addressbook sources/groups list actions: Add group, Delete group, Rename group, Save search, Delete search, (from Kolab:) Add, Delete, Rename, Remove from list, Show CardDAV URL, Manage folders.

**Comment by alecpl** [comment]
So, the layout proposed above could work for desktop/tablets (where content frame is not hidden). For phones I propose:
```
-----------------------------------------------------
|   (icon)   |   (icon)   |   (icon)   |   (icon)   |
|   action   |  optional  |  optional  |   more...  |
-----------------------------------------------------
|  <<       <       X - Y of ZZZZ       >       >>  |
-----------------------------------------------------
```
So, there will be 1 to 4 icons. The one on the right will be a "more actions popup", added when there's more than four actions. Buttons from the left could be: Add, Delete. For mail messages that could be: Reply, Reply All, Delete, More. So, Compose could be a special button in header instead of footer.
Another thing to consider is if we should limit the number of buttons to three on very small screen like 240px and increase to five on bigger width like 480px.
Or there are other options, especially considering #16 and #18?

**Comment by alecpl** [comment]
Oh, I forgot that we also have a page jump input for the messages list. Used to move to the specified page of the list.

**Comment by pom2ter** [comment]
4 icons would equal to 120px space each on a 480px screen which is a sweet spot (having a max of 120px between icons). I wouldnt go higher than 4. And they could all be centered in a 120px container. 

<pre>
------------------------------------------------------------------
|    (icon)     |    (icon)     |     (icon)     |     (icon)    |
| <--120 px-->  | <--120 px-->  |  <--120 px-->  |  <--120 px--> |
------------------------------------------------------------------
</pre>

If you have less than 4, you could put them all on the left or right side.

<pre>
------------------------------------------------------------------
|                                     | (icon) | (icon) | (icon) |
|                                     |        |        |        |
------------------------------------------------------------------
</pre>

3 icons in a 240px width screen equals 80px which is probably the min-width for readability.

**Comment by johnajackson-zz** [comment]
I think that this proposed layout would work. We can just show less as proposed for smaller screen sizes.

**Comment by alecpl** [comment]
I chose a different solution. We now have a separate navigation bar below the list header. Also, most buttons from the footer were moved to the toolbar for consistency with mail UI. So, the list footer contains only selection/options buttons (and quota widget).

This makes it simpler in implementation and more intuitive across different screen sizes.
