### ISSUE TITLE
[mobile] Trying to change settings in "mail">"options" opens Apple drown-down-menu instead of drop-down-menu IN the email program

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#80]
Steps to reproduce:
Open "mail" area, then click on "option". Then e.g. click on the field below "sorting column" in order to select an option.

Actual results:
The (in my case) Apple/iOs "drop down menu" (in the form of some "3D roll", which is quite unpractical) opens instead of a drop-down-menu in the email program.

Expected/desired results:
A (normal!) drop-down-menu offering the possible options should open in the email program.

https://git.kolab.org/file/data/hcwtciqd4fwyvzkikhlr/PHID-FILE-rghvp42w3e2bbcpx6yee/IMG_4551.PNG

**Comment by alecpl** [comment]
So, you say iOS's <select> widget is unpractical? I'm not sure we should overwrite browser's default widgets for common form elements. On the other hand we already overwrite checkboxes. Bootstrap provides dropdown widget, but it does not have a code to convert <select> element into dropdown.

**Comment by alecpl** [comment]
Possible replacement could be https://github.com/silviomoreto/bootstrap-select. But looks heavy.

**Comment by alecpl** [comment]
We have pretty selects now, but it's not working on iOS. So, we stay with the browser default. Closing as wontfix.
