### ISSUE TITLE
bad icon: @ symbol not apt for signature function

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#81]
the 'signature' function is represented by the @ symbol

a writing pen or something similar would be better

**Comment by alecpl** [comment]
The symbol comes from "Identities" which keep signatures, but I agree that even for identities the icon is not perfect.

**Comment by johndoh** [comment]
this might work for identities https://fontawesome.com/icons/id-badge

**Comment by alecpl** [comment]
Yes, but anything with user image can be confusing in mail compose screen. On the other hand we use a label "Signature", so maybe that could work.

**Comment by alecpl** [comment]
Fixed with https://fontawesome.com/icons/id-card icon.
