### ISSUE TITLE
[mobile] Inserting elements into an e-mail: window is cut off

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#83]
Steps to reproduce:
Problem with both android and IOS

compose new e-mail
tap the small plus above the text field
tap one of the given options e.g.:"Bild" (= Image)
Actual results:
The window to choose the object is cut off on the right side so that there is no button visible with which you can choose a file from your mobile phone (like in the desktop version). The window cannot be moved either.

https://git.kolab.org/file/data/onyk76tkpdyk4opqegtq/PHID-FILE-tloqs7l2jpuw4z23xklj/Screenshot_2017-11-30-12-40-20.png
https://git.kolab.org/file/data/rof7pwwo5ovpriwzd3hj/PHID-FILE-33manr2qn7cgqe4f2ubw/IMG_7607.PNG

**Comment by alecpl** [comment]
Yes. TinyMCE version we use does not really support mobile. We'll have to test most recent release.

**Comment by alecpl** [comment]
Fixed.
