### ISSUE TITLE
[mobile] No information displayed when opening "About" on iOS/iPhone

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#84]
Steps to reproduce:
Open main menu, click on "About"

Actual results:
On iOs/iPhones, no text/information is displayed, only a white screen appears. (see screenshot)
https://git.kolab.org/file/data/43nwjgbydgiu6rbgtzbj/PHID-FILE-z5sqijp6g6keknb4teno/IMG_4591.PNG

Expected results:
Like on Android phones, where this is working, the corresponding information/text to "About" should be displayed.

**Comment by alecpl** [comment]
There's something wrong with iframes on iOS.

**Comment by alecpl** [comment]
Works for me. Must be something with the demo you used.
