### ISSUE TITLE
[mobile] main menue as side drawer menue

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#85]
The main menue is displayed in fullscreen and makes the impression of being an extra page.
One could therefor try to exit the menue via the back button of one's phone, what does not work.

If the main menue would be presentetd as side draw menue, it would be clear that it is infact a menue and not a page.

**Comment by alecpl** [comment]
I kind of like the way it's different than other menus. Something to consider by a designer.

**Comment by alecpl** [comment]
Implemented as any other menu. Fixed.
