### ISSUE TITLE
[mobile] No feedback whether a contact has been added successfully to the address bar

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#86]
Steps to reproduce:

1.  compose new e-mail
2. tap the menu item "Kontakte" (= Contacts) in the menu that is marked by three dots
3. choose a contact
4 . tap "To+" at the bottom

Actual results:
There is no feedback displayed whether the chosen contact has been added successfully to To+ --> You have to go back to the new e-mail to find it out.

Expected result:
The software displays a feedback like "Contact has been added to To+ successfully" or similar.
or
The contact window closes and you are back at the main composer view

**Comment by alecpl** [comment]
Done.
