### ISSUE TITLE
[mobile] E-Mail content is cut off

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#87]
How to reproduce:
Click on mail to read

Actual Outcome:
Email is partially cut off and window cannot be adjusted in order to read the full e-mail

Expected Outcome:
Mail display is automatically adjusted to the screen size with full email content

This problem appeared on ios and android.

https://git.kolab.org/file/data/tomppxdz2kv2qroho5sz/PHID-FILE-ufu2hvqws5gki5jlxsbw/IMG_7619.PNG

**Comment by alecpl** [comment]
I confirm that all iframes aren't scrollable on iOS. There's a hack for this, but requires a wrapper element.

**Comment by alecpl** [comment]
On Android the content scrolls for me. There's of course problem with page width, but I think it will depend on the specific email content. E.g. it may require some screen width if the content wasn't designed to be responsive. I'm not yet sure what we could do in such a case.

**Comment by alecpl** [comment]
This wasn't trivial, but It should be fixed now.
