### ISSUE TITLE
[Mobile] no automatic zoom out 

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#88]
Steps to reproduce:
IOS Problem only
Typing in textfields

For example:
Search for a contact via search function.

Actual results:
Window zooms in. But after confirming the input the window does not automatically zoom out again to original size. This leads to cut-off functions on the screen. You have to zoom out manually.

Expected results
I would expect that the window zooms back to normal size after confirming the input.

**Comment by mbohlender** [comment]
https://git.kolab.org/file/data/7xyqmkx5n7erx7aadnm2/PHID-FILE-nwhlkqjdiisoh3piuj2h/IMG_7597.PNG
https://git.kolab.org/file/data/aa3poh7pc6nns4g3pc7s/PHID-FILE-cbrhscyc4htwodabzjm2/IMG_7598.PNG
https://git.kolab.org/file/data/aa3poh7pc6nns4g3pc7s/PHID-FILE-cbrhscyc4htwodabzjm2/IMG_7598.PNG

**Comment by alecpl** [comment]
Fixed in #132
