### ISSUE TITLE
Use font-awesome icons

### ISSUE THREAD

**Issue by thomascube** [roundcube/elastic#9]
We had this request already for the current Roundcube skins. Font Awesome offers a very versatile iconset and having it as part of the basic theme will make it easier for plugin developers to seamlessly integrate their work into the UI.

**Comment by alecpl** [comment]
We're already using it via semantic-ui icon classes (https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/icon.css) and as :before style https://github.com/roundcube/elastic/blob/master/styles.css#L494

Do you propose to use "raw font-awesome distribution"?

**Comment by thomascube** [comment]
I think it's more convenient to use FA directly using their LESS mixins and with their fa-* classes instead of manually setting character codes to :before selectors.

**Comment by alecpl** [comment]
We could for buttons, but handling lists (e.g. .listing.iconized) would be problematic. Or do you mean keep using :before but replace `content` property with some less?

**Comment by thomascube** [comment]
font-awesome LESS offers named variables for the content property. See https://github.com/FortAwesome/Font-Awesome/blob/master/less/icons.less We should at least use these in our sources for convenience reasons.

**Comment by alecpl** [comment]
Means it should be enough to just import https://github.com/FortAwesome/Font-Awesome/blob/master/less/variables.less into our less file and we can use these font variables.

**Comment by alecpl** [comment]
Done.
