### ISSUE TITLE
[feature request] drag&drop for Inline pictures

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#92]
Some people where missing this functionality. 
I don't know if it is a good thing to encourage inline pictures.

**Comment by alecpl** [comment]
You mean drag-n-drop an image from desktop into message composing area? This works in HTML mode. Supporting this in plain text mode would be quite complicated.

**Comment by mbohlender** [comment]
yes. in html mode.
it does not work for me. and it was reported by two students. so it did not work for them as well.
d&d to the attachment area works, to the composer area does not.

**Comment by alecpl** [comment]
What browsers/versions?

**Comment by mbohlender** [comment]
Chromium 62.0.3202.94 fails
Firefox 57.0 works but has a different issue. I'll open another ticket for it

**Comment by alecpl** [comment]
Works for me on my Roundcube instance. This bug is caused by Content Security Policy configuration of your demo instance. I created a ticket for KolabNow to fix that.
