### ISSUE TITLE
inconsistent outcomes of the drag&drop function (e-mail vs. contacts)

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#93]
Steps to reproduce & Actual results

drag&drop an e-mail into a folder => e-mail is moved into the folder
drag&drop a contact into a contact group => the contact is copied into the group

Expected result

The drag&drop funbction should have a similar result all over the program

solution
Folders and groups represent two different conceptual models. Hence the two different outcomes of the drag&drop function may make sense. Nonetheless a short feedback about what has happened (e-mail has been moved to xy, Contact has been added to the group xy) would be helpful.

**Comment by alecpl** [comment]
I cannot confirm that.

There is feedback message for contacts and email drop actions.

In Addressbook we have groups and books. So, dropping a contact to another addressbook is a move action, as well as dropping a contact to a group in another book. Dropping a contact into a group in the same book is assigning action. All of them provide feedback.

**Comment by mbohlender** [comment]
I can't reproduce it myself. I will check with the students who reported it.
