### ISSUE TITLE
"mark" button displayed as activated, even though no email is selected

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#94]
How to reproduce:

1. open inbox view
2. make sure no email is selected

Actual result:
"mark" button displayed as activated

https://git.kolab.org/file/data/jwaeao76jwltkljhwszt/PHID-FILE-3l5mqsgaapr3m5qqjnv4/Screenshot_%2810%29.png

Expected result: 
No action is possible so it should be displayed as disabled.

**Comment by alecpl** [comment]
This is the case for most of buttons that onclick display a menu. However, I agree that it should be grayed out and that should be doable.

**Comment by alecpl** [comment]
Fixed.
