### ISSUE TITLE
"Register protocol handler for mailto: links" seems to do nothing under chrome/android

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#96]
how to reproduce:
on android:
go to settings -> preferences-> user interface
click on  "Register protocol handler for mailto: links"

result:
nothing happens

probably the same for iOS.
Could we hide this for browsers/OSs that do not support this?

**Comment by alecpl** [comment]
This is the same in IE/Edge. We do feature support detection and disable the link. I wouldn't like to hide this feature. Maybe it would be better to display an error "Feature not supported in this web browser". On the other hand we already hide some UI elements...

**Comment by alecpl** [comment]
Moved to https://github.com/roundcube/roundcubemail/issues/6079.
