### ISSUE TITLE
[mobile] file attached to email cannot be opened

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#98]
How to reproduce:
Open Email with file attached (pdf). 
Try to click on the file directly or klick on the little arrow to open the menu "open"/"download" and try to open the file.

Actual Outcome:
When opening the email (either via the little arrow/menu or directly on the link) no content is displayed. 
https://git.kolab.org/file/data/uh2fxflpydet5z2y75li/PHID-FILE-lshbm2huzlfu4uaxlf7l/IMG_8169.PNG

Only when the file is downloaded it works.

Expected Outcome:
the content of the file is displayed when trying to open it.

This problem occurred on ios.
Works on android

**Comment by alecpl** [comment]
The same as in #84.

**Comment by alecpl** [comment]
Works for me. Must be something with the demo you used.
